### ISSUE TITLE
Filetree column

### ISSUE THREAD

**Issue by joostdevries** [ember-cli/ember-twiddle#10]
With column no. next to open files. @kevinrudyanderson if you could someday create a mock for this that would be awesome.

**Comment by kevinrudyanderson** [comment]
Noted

**Comment by eccegordo** [comment]
:+1:  I think the overall UI could use a little more visual definition. If feasible something approaching atom or sublime editor sidebar would make this much more approachable.

<img width="907" alt="ember-cli-project" src="https://cloud.githubusercontent.com/assets/497659/8613789/a18ec312-2697-11e5-9d30-8bb3854e1e1a.png">

**Comment by miguelcobain** [comment]
Suggestion:

What if we throw away one of the columns and use it as a file tree?
We would have only one column for file editing. Switching files would be done through tabs.
I'm basically suggesting a UI like Atom or any other text editor. :)

**Comment by joostdevries** [comment]
That approach would optimize for editing but not for sharing, which is at least as important IMO.

**Comment by miguelcobain** [comment]
@joostdevries Can you elaborate on the "not for sharing" part?

I assume you're saying its worse for sharing because you don't see multiple files simultaneously?

**Comment by joostdevries** [comment]
@miguelcobain Yeah, #123 is about that. In a lot of cases, you show a specific state of a twiddle.
