### ISSUE TITLE
Tests fail when gh token is still set locally

### ISSUE THREAD

**Issue by joostdevries** [ember-cli/ember-twiddle#102]
### Reproduce
- Run local server + gatekeeper
- Login
- Run tests using `/tests`
- App will try GH user API which is not yet mocked

**Comment by rwjblue** [comment]
Does `ember test --server` work locally?

**Comment by joostdevries** [comment]
It's a test problem, we don't mock the GH user API (which is fine normally) but if there's a `fiddle_gh_session` in localstorage (yes - extremely ill-named), it will call the GH user API.

**Comment by joostdevries** [comment]
Think it's also better to store the token in a Cookie rather than LS.

**Comment by Gaurav0** [comment]
Fixed by #112
