### ISSUE TITLE
Ability to type route name in the twiddle address bar

### ISSUE THREAD

**Issue by abidmix** [ember-cli/ember-twiddle#118]
The default url bar at present is a div which is ready only. It would be nice to type a known route and be taken to it during a demo in twiddle. I have created a gist and a  twiddle http://ember-twiddle.com/ec81fea57d0555c1859a  to demonstrate the desired functionality

**Comment by JKGisMe** [comment]
+1 
I went to go experiment with different path related stuffs in a twiddle and realized I couldn't really interact with it much to see if what I did in the router was working how I wanted. Making the existing url bar interactive would be super cool.

**Comment by abidmix** [comment]
I downloaded the source code, rummaged the internals and was able to achieve the functionality, with some help from my EmberNYC meetup colleagues. I will be submitting a pull request soon. Check out the interactive url bar in action at  http://ember-twiddle.com/ec81fea57d0555c1859a

**Comment by rwjblue** [comment]
Awesome!

**Comment by Gaurav0** [comment]
@abidmix So to turn this into a PR, we need to make the existing url bar a textfield input box, and when the user types, post a message to the app inside the iframe, and in the iframe, on postmessage, transition the router to the route entered.

**Comment by abidmix** [comment]
Thanks @rwjblue.   @Gaurav0 ,I agree. I will be setting up my dev environment in accordance wth the instructions in the contributing.md document. I will shout if I need help in wiring the postmessage to the iframe.

**Comment by JKGisMe** [comment]
I love the error message `Oops.... it seems you forgot to define this route in your router.js`

**Comment by alexspeller** [comment]
I suspect the simplest / cleanest way to implement this might be by injecting a custom location implementation

**Comment by Gaurav0** [comment]
Fixed by #248
