### ISSUE TITLE
Enhancement: Having a splash screen or loading message will be good

### ISSUE THREAD

**Issue by phkavitha** [ember-cli/ember-twiddle#120]
We can have a splash screen or a simple loading progress bar during the initial loading of the entire application. Now, the plain screen with only the GitHub ribbon looks little odd. 
![screen shot 2015-07-31 at 11 21 03 pm](https://cloud.githubusercontent.com/assets/2657473/9020459/53224942-37db-11e5-8714-5df5bf02c48b.png)

If we can decide on the how it has be showed, then I would like to develop it.

**Comment by rwjblue** [comment]
There are at least two main issues:

* Loading a gist is somewhat slow.  For this we can use Ember's loading template system as described in http://guides.emberjs.com/v1.13.0/routing/loading-and-error-substates/. It should be as "easy" (famous last words) as adding a `app/loading/template.hbs` with a nice spinner or something.
* Loading the `vendor.js` and `ember-twiddle.js` files.  To add a spinner/loading indicator here, we have to do it in plain HTML before loading `vendor.js` and `ember-twiddle.js` (around [here](https://github.com/ember-cli/ember-twiddle/blob/master/app/index.html#L26-L27)).

**Comment by acorncom** [comment]
Using ember-cli-pace for the second item would help save a lot of time ...

**Comment by acorncom** [comment]
This is done at this point I believe

**Comment by alexspeller** [comment]
Yup, it's right there
