### ISSUE TITLE
Share with specific files shown

### ISSUE THREAD

**Issue by HeroicEric** [ember-cli/ember-twiddle#123]
I usually use emberjs.jsbin.com to quickly show little examples to people or try them out for myself. When sharing with somebody else, it's important to be able to link them to the code that is specific to what I'm trying to show.

When trying to share twiddles with others, I feel like I need to also tell them which files to open up to see what I'm talking about.

For example, I want to link somebody to http://ember-twiddle.com/da9d9673a1102ba0a476 but I'd like to have the `index/route.js` and `index/template.hbs` be the files that are opened when they get there.

I don't think this would be too difficult to implement right now using queryParams but it may get more complicated if https://github.com/ember-cli/ember-twiddle/issues/122 is done

**Comment by acorncom** [comment]
This probably falls under the same general issue.  It'd be nice to be able to highlight certain lines of code within a Twiddle (like can be done with Github). Could get complicated if we tried to highlight multiple lines in multiple panes though ...

**Comment by HeroicEric** [comment]
@acorncom I think that would be a separate feature to be worked on separately. That would add a lot to the complexity of my original issue

**Comment by acorncom** [comment]
@HeroicEric Sounds good.  Opening a separate issue, sorry to pollute this one ...

**Comment by HeroicEric** [comment]
This was completed by https://github.com/ember-cli/ember-twiddle/pull/296
