### ISSUE TITLE
Kill the Wiki

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-twiddle#125]

**Comment by joostdevries** [comment]
@Gaurav0 Can we merge this into #108 ?

**Comment by joostdevries** [comment]
also: not sure whether to use Wiki or have instructions in-app

**Comment by Gaurav0** [comment]
Well, it is kinda a separate issue that the wiki is out of date. Also I think instructions need to be provided in app.

**Comment by joostdevries** [comment]
I'd rather kill the wiki and have instructions/info in one place.

**Comment by Gaurav0** [comment]
Ok.

**Comment by joostdevries** [comment]
killed with :fire:
