### ISSUE TITLE
Confirmation beforeUnload if unsaved changes

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-twiddle#126]
If the user has made unsaved changes, confirm if he tries to close the tab / window or navigate.

**Comment by SaladFork** [comment]
It would be nice if there were a few more safeguards to protect against losing a twiddle to a reload or accidental navigate. What about saving the contents of the code in local storage similar to [TDD bin](http://tddbin.com/)?

**Comment by Gaurav0** [comment]
@SaladFork Can't really do that until we have gist revision management, or at least the ability to duplicate twiddles, because there would be no way to elect NOT to update a gist.

Confirmation dialogs can be annoying though. Other suggestions are welcome.

**Comment by shankarsridhar** [comment]
@Gaurav0 @SaladFork  How about `autosave` probably with a checkbox ?

**Comment by Gaurav0** [comment]
@shankarsridhar See issue #64

**Comment by workmanw** [comment]
Bump. Definitely needed. Just lost 20 minutes of work by naively clicking "My Recent Twiddles" from the profile menu.

**Comment by Gaurav0** [comment]
Fixed by #365
