### ISSUE TITLE
Make it embeddable

### ISSUE THREAD

**Issue by joostdevries** [ember-cli/ember-twiddle#13]
So we can use it in the Ember guides

**Comment by Gaurav0** [comment]
Do we just need to generate code to load it in an iframe, or is there more to this?

**Comment by stefanpenner** [comment]
@Gaurav0 I suspect it may also need some style tweaks.  Typically the embedded examples are presented in a smaller viewport.

**Comment by joostdevries** [comment]
@Gaurav0 yeah when @kevinrudyanderson gets back from his well-earned vacation I hope this can be part of the next design iteration.
