### ISSUE TITLE
Save to Gist Github doesn't seem to work

### ISSUE THREAD

**Issue by eccegordo** [ember-cli/ember-twiddle#136]
Maybe this is already being discussed. But that save gist option in menu doesn't seem to do anything AFAIK. Logged in and didn't see a change in UI, nor could I find any gists on my github.

Also, not clear how to share (future feature?). Seems like it should share a URL for easy copy and paste.

Also, not clear how to change URL paths or routes. Is that what the little bar with the slash in the output pane is for? Didn't seem to work for me.

Is there a plan to support regular urls like this as part of the sharing story:

```
http://ember-twiddle.com/xyz-gist-sha1/foo/bar

xyz-gist-sha1 => the specific twiddle home (sha1? or counter?)
foo/bar       => routes specific to the twiddle example itself
```

**Comment by Gaurav0** [comment]
I'm sorry you are having trouble. It seems to work for me. A few quick questions:

1. When you signed in, did your name appear? Or was it still anonymous?
2. Do you see your avatar?
3. When you click save to github, do you notice a message on the bottom right?
4. Does the unsaved indicator change?

Also, could you try it again with the console open, and let me know if there are any error messages when you click save?

**Comment by eccegordo** [comment]
OK tried again with a fresh twiddle and the save to gist part works. 

The previous one had been open over night and just tried to save but maybe I didn't do it right or some session timeout.

I see the share option now. So what the plan for versioning? JSBin had the idea of incrementing.

Also, the forking option seems to fail for me.

<img width="1066" alt="embertwiddle" src="https://cloud.githubusercontent.com/assets/497659/9134896/72cfcca6-3cbd-11e5-9464-3b394e471fd8.png">

**Comment by Gaurav0** [comment]
Again, sorry you are having trouble. Currently, forking only works if you don't already own the gist and haven't already forked it. We need to work on better error messages.

**Comment by joostdevries** [comment]
> We need to work on better error messages.
agreed :-)
