### ISSUE TITLE
Add support for commenting/uncommenting

### ISSUE THREAD

**Issue by HeroicEric** [ember-cli/ember-twiddle#143]
- [x] Allows commeting/uncommenting single lines
- [x] Allows commenting/uncommenting multiple lines

Looks like there is an addon for codemirror that adds support for this https://codemirror.net/doc/manual.html

**Comment by Gaurav0** [comment]
I'm confused. Doesn't JavaScript let you do this?

**Comment by HeroicEric** [comment]
@Gaurav0 I'm talking about inside the file editor panes. For example, on jsbin you can use `cmd + /` to comment/uncomment

**Comment by joostdevries** [comment]
This should be fairly doalbe by adding the `comment` addon to codemirror (probably just `import` ing it). http://codemirror.net/doc/manual.html#addons

**Comment by gokatz** [comment]
@Gaurav0 and @joostdevries, I would love to give this a try :)
