### ISSUE TITLE
Shift Mode -> Keystroke Mode?

### ISSUE THREAD

**Issue by acorncom** [ember-cli/ember-twiddle#163]
I'd thought it might adjust styling, but didn't.  If it changes keystroke modes, might be worth tweaking the label on that.

**Comment by Gaurav0** [comment]
Agreed. :+1:

Good for new contributors.

**Comment by vikram7** [comment]
PR [here](https://github.com/ember-cli/ember-twiddle/pull/168/files) for this change.
