### ISSUE TITLE
Support Tests

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-twiddle#178]
Allow users to write and execute Ember unit, integration, and acceptance tests.

**Comment by rwjblue** [comment]
Should already be possible, but I'll try to whip up an example when I'm back at a keyboard...

**Comment by Gaurav0** [comment]
https://ember-twiddle.com/4ecd2437e883e0bfe684?route=%2Ftests

**Comment by Gaurav0** [comment]
Fixed by #298
