### ISSUE TITLE
How to add configuration variables to the App instance?

### ISSUE THREAD

**Issue by patrickarlt** [ember-cli/ember-twiddle#182]
I'm working on debugging an issue with http://ember-twiddle.com/6f009294d78737f7f56e and I need to add `customEvents` to my app config for it to work in Twiddle.

Locally I am doing this in `config/environment.js` like this (full file is [here](https://gist.github.com/patrickarlt/84d30dd1c8156efd6e9e#file-environment-js-L17-L22)).

```js
// ...
    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
      customEvents: {
        rateitem: 'rateitem'
      }
    }
// ...
```

Is there some way to pass options like `customEvents` to the application?

**Comment by Gaurav0** [comment]
At this time this is not supported. Leaving this issue open for anyone to work on.

**Comment by piotrpalek** [comment]
@Gaurav0 is there a reason we're not using a user supplied `config/environment.js` file or isn't it just implemented yet? If it's the latter I could add support for it, that should fix this issue.

**Comment by Gaurav0** [comment]
@piotrpalek The main reason is that there is no node.js environment available. Any config/environment.js would have to be evaluated in the browser and thus would have a different structure and semantics. Given that limitation, we're putting all our pre-build configuration in twiddle.json

**Comment by piotrpalek** [comment]
@Gaurav0 yeah I was just thinking that having an `environment.js` would be familiar while behaving mostly the same (we could evaluate it before all other files). But a json file makes more sense here since we're not in node. So I think a good solution for this would be to have an `environment` key in `twiddle.json` which would get merged into the "internal" environment file.

**Comment by joostdevries** [comment]
@Gaurav0 I believe this was implemented in #397.

**Comment by allthesignals** [comment]
Is this documented anywhere? I have an addon that looks in environment.js for some configuration in the top level of properties (not under APP or EmberENV). It can't seem to find anything I set on it. Here is how the addon is finding the configuration:

const mbglConfig = getOwner(this).resolveRegistration('config:environment')['mapbox-gl'];

**Comment by Gaurav0** [comment]
No, documentation is required. Use the ENV key.

**Comment by allthesignals** [comment]
Thanks, @Gaurav0!
