### ISSUE TITLE
Change Anonymous menu drop down -> "Sign In"

### ISSUE THREAD

**Issue by acorncom** [ember-cli/ember-twiddle#183]
Having the Anonymous drop down with a "Sign In" option makes it less clear that there is "sign in" option available.  Could we change it to say "Sign In" by default and then change it to a drop down menu once someone is logged in?

**Comment by JKGisMe** [comment]
I can do this today if no one is working on it...

**Comment by Gaurav0** [comment]
Yes no one is working on it
