### ISSUE TITLE
Main Header is Cut Off

### ISSUE THREAD

**Issue by wifelette** [ember-cli/ember-twiddle#187]
![2015-09-03_14-28-17](https://cloud.githubusercontent.com/assets/25433/9671514/44f81680-5248-11e5-99fe-056988a9bd4c.png)

I remember pointing out when we worked on the redesign that this was a bug, so it's probably still there from before. Size of the browser window doesn't seem to matter.

**Comment by Gaurav0** [comment]
We've "fixed" this one twice already. :(

**Comment by JKGisMe** [comment]
Ya I thought I fixed it by reserving the space even when no avatar is present. I had noticed it was back again in my fork but I was wishful thinking it had to do with my fork somehow

**Comment by Gaurav0** [comment]
Fixed by PR #207
