### ISSUE TITLE
Add "FEATURES" section to twiddle.json

### ISSUE THREAD

**Issue by chancancode** [ember-cli/ember-twiddle#188]
so people can use experimental features on their fiddles

Here is a quick hack to do this today: https://gist.github.com/chancancode/225639b3144dd82f3b6d

The key is to add an `EmberENV` override as a dependency before Ember: https://cdn.rawgit.com/chancancode/5b7b95b6268d51cdcaae/raw/92e0654083305c73cd601381a6cea705be9f8890/hax.js

**Comment by pangratz** [comment]
Since #219 got merged, I guess this issue can be closed :tada:

**Comment by rwjblue** [comment]
Thanks @pangratz!
