### ISSUE TITLE
Add HTMLbars helper blueprint

### ISSUE THREAD

**Issue by Kuzirashi** [ember-cli/ember-twiddle#191]
It would be useful to have possibility to add new file and add new helper, so demos could be more complete.

**Comment by mthouve** [comment]
I'd like to see this as well.

**Comment by knownasilya** [comment]
I'd add it, but is there a server side part that isn't in his repo? Just looking for where the blueprints come from in `gist-file` model.

**Comment by pangratz** [comment]
@knownasilya I think #213 is a good starting point on how to add new blueprints ...

**Comment by knownasilya** [comment]
Thanks @pangratz

**Comment by Gaurav0** [comment]
@knownasilya The blueprints come from the ember-cli github repository in the blueprints directory. These are copied during the build process for ember-twiddle in ember-cli-build.js
