### ISSUE TITLE
Mobile/low width layout is borked

### ISSUE THREAD

**Issue by elwayman02** [ember-cli/ember-twiddle#195]
This is caused by `<div class="handle" style="cursor: col-resize;"></div>`, which takes up 100% of the screen height when the responsive grid hits its breakpoints, causing humongous whitespace between the panels. These handles need to either be removed entirely on small screen sizes or have styles to make them display horizontally instead of vertically so they can be used to resize the height of the panes (which are way too tall in the 1-column layout).

I recommend looking into [ember-responsive](https://github.com/freshbooks/ember-responsive) to handle your screen size breakpoints and a UI framework with a better responsive than Bootstrap (I would use ember-paper).

![ember_twiddle](https://cloud.githubusercontent.com/assets/1325482/9942226/cdc927d8-5d2e-11e5-97b6-3221bf9fa22d.png)

**Comment by Gaurav0** [comment]
Fixed by #196
