### ISSUE TITLE
Escaping \{{mustaches}} does not work

### ISSUE THREAD

**Issue by code0100fun** [ember-cli/ember-twiddle#205]
Can't escape them on Ember Twiddle:
http://ember-twiddle.com/26f032c674b360cb739c

Here is the same thing in a JSBin:
http://emberjs.jsbin.com/padehe/edit?html,js,output

**Comment by Gaurav0** [comment]
Workaround: Use two slashes: http://ember-twiddle.com/bf3ed376b76baf621b8c
