### ISSUE TITLE
Fixtures is giving me CORS error

### ISSUE THREAD

**Issue by aalasolutions** [ember-cli/ember-twiddle#209]
I have created a fixture

    import DS from 'ember-data';

    var group =  DS.Model.extend({
      group_name: DS.attr('string'),
      links: DS.hasMany('link', {inverse: null, async: true})
    });
    
    group.reopenClass({
        FIXTURES: [
          { id: 1, group_name: 'Webmaster'},
          { id: 2, group_name: 'Employee'}
        ]
    });
    
    export default group;

and used it like

    model:function () {
        return this.store.find('group');
    },

But it is giving me error 

    "NetworkError: 403 Forbidden - http://ember-twiddle.com/groups"

**Comment by Gaurav0** [comment]
You need to use the FixtureAdapter.
