### ISSUE TITLE
Redirect Uri Mismatch

### ISSUE THREAD

**Issue by mattmazzola** [ember-cli/ember-twiddle#214]
When clicking 'sign-in' the popup opens and authentication succeeds but there is an error during the redirect.

The end result is that the ember-twiddle opens inside the popup, but torii never detects the uri change to capture the token.

You can see the error in the url of the popup:
`http://ember-twiddle.com/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=STATE`

https://developer.github.com/v3/oauth/#redirect-uri-mismatch

I can manually copy the fiddle_gh_session token into the original window to verify that the authentication works.

**Comment by Gaurav0** [comment]
So the redirect is to https://ember-twiddle.com but you went to http://ember-twiddle.com @joostdevries Is there a way to avoid this problem?

**Comment by mattmazzola** [comment]
Ah yea that seems to be it. I had been going to the ember twiddle site by clicking the google search result which uses https protocol.  If you attempt to sign in from https it redirects to http which fails. If I manually type in the non-https url and attempt the sign in, it works fine.

I would suspect you could change the redirect url to use https, and then setup a redirect from http to https so people will always be on https.

**Comment by joostdevries** [comment]
hmmz. will look into this, should be able to fix this with either cloudflare or s3.

**Comment by jfelchner** [comment]
Yeah I'm having serious sign in issues as well.  Sometimes it'll open in the popup, other times the popup will open, then close (presumably because I'm already logged into Github), and then the request to `https://ember-twiddle.herokuapp.com/authenticate/<token>` will `pend` for a minute or so then time out.

**Comment by jfelchner** [comment]
![image](https://cloud.githubusercontent.com/assets/285582/10617972/ff0a577c-7732-11e5-93b3-6d56bae61047.png)

**Comment by jfelchner** [comment]
![image](https://cloud.githubusercontent.com/assets/285582/10617980/0eb2fe4a-7733-11e5-97b4-4050204cbe6c.png)

**Comment by joostdevries** [comment]
fixed. the slow response from heroku makes sense since it's still a free instance. If this continues to be an issue, please reopen this and I'll look at getting it upscaled.
