### ISSUE TITLE
Changing Ember version, does not update ember-template-compiler version.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-twiddle#227]
/cc @pangratz 

![changing-versions](https://cloud.githubusercontent.com/assets/12637/10678005/973fb9dc-78dd-11e5-98ef-3b85b9a454b7.gif)

**Comment by pangratz** [comment]
I'm on it.

**Comment by pangratz** [comment]
This can be closed since #228 has been merged ...
