### ISSUE TITLE
avatar not scaled

### ISSUE THREAD

**Issue by brianally** [ember-cli/ember-twiddle#246]
Screenshot with & without `overflow: hidden` shows that it's pulling in a 420x420 image but not scaling it. The img tag needs w & h attrs or it could be handled in css (better, imo).

For those curious about the location bar see #214 .

![screen shot 2015-10-27 at 3 36 48 am](https://cloud.githubusercontent.com/assets/8657255/10752254/f9c70050-7c5d-11e5-9fbc-c0fd4c54d837.png)

**Comment by Gaurav0** [comment]
Is this only an issue in the redirect page?

**Comment by brianally** [comment]
It doesn't appear to be. In this case, the twiddle has opened inside the oauth popup, per #214, but the markup is pretty clear: the img is not being resized. It either needs width&height or the width could be set in css. The latter would allow for resizing at breakpoints.

**Comment by Gaurav0** [comment]
Unable to reproduce on http://ember-twiddle.com

**Comment by brianally** [comment]
Your avatar displays correctly? Still doing it for me. Inspect the avatar image. It does not have any dimensions but the wrapper has `overflow: hidden` so only the top-left corner of the image is visible.

**Comment by brianally** [comment]
ok, hold the phone! I had not set a GH avatar, so was getting the default coloured blocks. In that case, GH returns a 420x420 image. However, i've just uploaded an image(gort, as here) and GH now returns a 32x32 image. Unfortunately, there doesn't seem to be a way to undo one's avatar without overwriting it with another.

So, the problem only manifests if a user does not have a specific avatar set. The safe thing to do, then, would be to include a style rule to explicitly size the image.

If you want to see this in action i suppose you could create a dummy GH acct. and not upload an avatar. But then, you might have issues with the oauth popup if you don't delete cookies. Maybe more trouble than its worth.

**Comment by Gaurav0** [comment]
:+1: Good for new contributors.
