### ISSUE TITLE
Show the css some love

### ISSUE THREAD

**Issue by brianally** [ember-cli/ember-twiddle#251]
I'm working on #236 but having things positioned absolute is a bit of a blocker. Also, the CSS could use some cleaning up. I'd like to propose a separate PR to:
- tidy up the css, especially creating $variables for many repeated properties.
- remove the absolute positioning

I'm not proposing any style changes, other than the positioning, just tidying. The end result should be that Twiddle appears identical to how it does now. Once that's done I can move back to sorting out the top nav.

**Comment by Gaurav0** [comment]
So the reason for all the absolute positioning was that elements needed to be the size of the viewport, i.e. have a dynamic height adjusted so the bottom of the element is at the bottom of the screen.

**Comment by brianally** [comment]
I was thinking about flexbox for this. I noticed there were are some flex rules in there already. I haven't looked at it carefully but my hunch is that the abs. pos. could be removed.

It may not be necessary, though. The issue comes down to what the nav should look like on mobile when it opens.

- basic dropdown
- pushes the content down
- slides in from side over top

The first works with abs. pos. but requires fiddly layout rules to keep the submenus reasonable. The second needs the absolute pos. removed. The last is probably the best option.

What's the target browser version support?

**Comment by Gaurav0** [comment]
I'm fine with sliding in from the side.

Our target is IE10+, Safari 6+, latest Chrome & Firefox. Currently IE isn't working due to #99

**Comment by locks** [comment]
Closing this issue due to the redesign effort currently underway.
