### ISSUE TITLE
Upgrade Ember to 2.0

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-twiddle#269]
Current issues preventing upgrade:

1. Some addon is throwing a silent error deprecation warning.
2. Instance Initializer deprecation warnings in acceptance tests.
3. Update blueprints

**Comment by rwjblue** [comment]
> Some addon is throwing a silent error deprecation warning.

This is not related to Ember itself (but rather it is related to ember-cli).

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-twiddle/pull/272
