### ISSUE TITLE
Safari doesn't load gists

### ISSUE THREAD

**Issue by alexspeller** [ember-cli/ember-twiddle#274]
Go to https://ember-twiddle.com/e96d14db68fd2d9c4ff5

You are redirected to the home page instead of showing the twiddle

**Comment by rwjblue** [comment]
Seems related to the S3 redirect shenanigans we are doing.

https://ember-twiddle.com/#/e96d14db68fd2d9c4ff5 works properly in Safari (but redirects to https://ember-twiddle.com/e96d14db68fd2d9c4ff5).

**Comment by alexspeller** [comment]
More discussion here https://stackoverflow.com/questions/16267339/s3-static-website-hosting-route-all-paths-to-index-html

**Comment by rwjblue** [comment]
Ya, I've used this S3 redirect pattern a few times.  I'm unsure what exactly is causing the issue in Safari though.

**Comment by Gaurav0** [comment]
http://stackoverflow.com/questions/34230581/ember-app-safari-router-behavior-is-different-on-page-refresh-or-direct-url-acc

**Comment by joostdevries** [comment]
This has now been fixed. It was caused by S3 redirecting over http by default (instead of the protocol used for the original request) and Safari trying to keep the QS data safe. Which is actually quite nice if you think about it.

**Comment by eccegordo** [comment]
FYI, I am still seeing this behavior sometimes when clicking certain twiddle links within slack. I have noticed in some examples with and without query params in the URL. Using Safari 9.0.1 OS X 10.11.1

Definitely manually inserting the hash/octothorpe/pound `#` character before the gist id seems to fix it. 

Did something change in S3 configuration perhaps?

Perhaps there should be an acceptance test of specific gists that can be period checked?
