### ISSUE TITLE
Navigate to prior route upon livereload.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-twiddle#287]
Demo Twiddle: https://ember-twiddle.com/fd76d04781aada411a32

Steps to reproduce:

1. click "something" link
2. notice URL listed in the internal url-bar (`/something`)
3. make a tiny change to any file (add a space to a template or something)
4. notice livereload has ran and navigated back to `/`

**Comment by Gaurav0** [comment]
This works correctly on canary.

**Comment by rwjblue** [comment]
Awesome, thanks for checking (I should've tested first, sorry about that).
