### ISSUE TITLE
Optionally disable auto-run

### ISSUE THREAD

**Issue by joostdevries** [ember-cli/ember-twiddle#30]
We should be careful w/ auto-run. Sometimes people make reproductions of infinite loops etc

**Comment by stefanpenner** [comment]
can someone share an example of this? I don't think we want to actually turn off auto-runs..

**Comment by stefanpenner** [comment]
> can someone share an example of this? I don't think we want to actually turn off auto-runs..

you know, i totally assumed this was related to embers run-loop autoruns. Carry on..

**Comment by joostdevries** [comment]
:+1:

**Comment by Gaurav0** [comment]
Fixed.
