### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by joostdevries** [ember-cli/ember-twiddle#307]
Is there anything preventing us from releasing 1.0? I personally have grown uncomfortable with (easily) publicly accessible projects being < 1.0 lately. For breaking changes we can always release 2.0 but 0.x should be preserved for stuff you have to build/run yourself IMO.

**Comment by Gaurav0** [comment]
We need addons. Seriously.

**Comment by rwjblue** [comment]
I'm happy to release as 1.0.0.  I promise that we will not run out of available integers for our major version :smile_cat:.

In the end consumer website version numbers don't really matter too much.  When was the last time you checked the version number on github.com or google.com? :smiling_imp:

**Comment by joostdevries** [comment]
@rwjblue correct point.

**Comment by stefanpenner** [comment]
@rwjblue I, unsure, I expect a proof demonstrating this :trollface:

**Comment by Gaurav0** [comment]
I don't think anyone's not using Twiddle because of a version number.

**Comment by rwjblue** [comment]
@stefanpenner - LOL

**Comment by lukesargeant** [comment]
@rwjblue is it worth closing this issue?

**Comment by lukesargeant** [comment]
Ignore my above comment. @locks suggested it's better to focus on issues I plan to contribute to rather than second guessing whether members should cull older issues. Apologies for the noise!

**Comment by acorncom** [comment]
I've just updated the v1 milestone with a few things Gaurav and I have been discussing. I'll go ahead and close this issue for now. @lukesargeant if you've got the umph to help push on things, would love to get your help on any of those. We're also discussing things some on the `-ember-twiddle` Slack channel if it's easier to brainstorm in there
