### ISSUE TITLE
Headers are not sent along with XHR from RESTAdapter

### ISSUE THREAD

**Issue by bryanmc** [ember-cli/ember-twiddle#309]
I created an adapter under `adapters/application.js` to connect to Parse backend.  This is already tested and working locally.

```javascript   
import Ember from 'ember';
import DS from 'ember-data';

export default DS.RESTAdapter.extend({
  host: 'https://api.parse.com',
  namespace: '1',
  headers: {
		'x-parse-application-id': 'Wxdq8qVv3mX1hQbvXOy8s...',
		'x-parse-rest-api-key': 'OOp32wR0jAweWOFiATu5wy...' 
  }, 

  (...)
```

Then in the route's model hook, comme d'hab...

```javascript   
import Ember from 'ember';

export default Ember.Route.extend({
  
  model: function(){
    
    return Ember.RSVP.hash({
        tweets: this.store.findAll('tweet')
    });

  }
  
});
```

It seems as if the header values are not being sent along with the request:

```  
curl 'https://api.parse.com/1/tweets' -X OPTIONS -H 'Pragma: no-cache' -H 'Access-Control-Request-Method: GET' -H 'Origin: null' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36' -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'Connection: keep-alive' -H 'Access-Control-Request-Headers: accept, x-parse-application-id, x-parse-rest-api-key' --compressed
```

The host and namespace are picked and applied properly, though...

**Comment by alexspeller** [comment]
That is a [CORS preflight request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) and you can't set headers on it. This is expected behaviour of ajax requests in modern browsers.

**Comment by bryanmc** [comment]
Apologies, I didn't quite understand what you meant.  I was referring to setting the headers on REST Adapter:

http://emberjs.com/api/data/classes/DS.RESTAdapter.html#toc_headers-customization

You can set headers as explained in the documentation.  I've never had issue with this, using the same the implementation as I normally use (setting headers within the adapter), except on Ember Twiddle.  Do you mean, specific to ET, this cannot be done?

And if not, do you have any suggestion as to how I might go about it?  Again thanks for your time.

**Comment by Gaurav0** [comment]
@bryanmc It's not specific to Ember Twiddle. You are making a request to a different domain than you are on, hence you making a CORS (Cross Origin Resource Sharing) request. Modern browsers have lots of security restrictions around that. Before making the actual request, the browser makes a CORS preflight request using OPTIONS to see if the actual request will be accepted. This preflight request cannot contain headers.

**Comment by mariogintili** [comment]
@alexspeller @Gaurav0 Are there any workarounds to add a header to it? I know that there shouldn't be any extra headers on that request however:

[There's a bug on AWS](https://forums.aws.amazon.com/thread.jspa?messageID=764227) Where endpoints with CORS enabled won't return the correct CORS headers if the preflighted response didn't return a status code beyond `200`. There are currently no workarounds from the AWS team from what I've read so far.

I know this isn't something akin to ember-twiddle/ember at all but I ran into this convo googling around and thought might be important to add 😄

**Comment by Gaurav0** [comment]
@mariogintili This is a browser restriction, if there is a workaround, please report it as a security issue. :)

In any case, you cannot make a CORS request to any site from Ember Twiddle unless it contains a header of access-control-allow-origin: '*', which no server should do.

**Comment by mariogintili** [comment]
@Gaurav0 true true! Came across all of that yesterday as I was going through all the information. AWS does have a workaround where you can set a mock which won't be using any form of auth, which will make preflight requests succeed 😄
