### ISSUE TITLE
Routes do not work in Firefox

### ISSUE THREAD

**Issue by sukima** [ember-cli/ember-twiddle#311]
Latest ember-twiddle 0.5.0 doesn't work in Firefox 43.0.4

Clicking a `link-to` or using the faux-URL bar. We get an `NS_ERROR_UNEXPECTED` and no output.

Verified that this feature is working in Chrome.

Example: https://ember-twiddle.com/3cc36a35de8dca267b0d?openFiles=about.template.hbs%2Crouter.js

<img width="1439" alt="screen shot 2016-01-29 at 12 54 24" src="https://cloud.githubusercontent.com/assets/70075/12683478/7ded807a-c687-11e5-9fd8-bf4f56fabfad.png">

**Comment by sukima** [comment]
Tried again with all popup/ad-blockers turned off. Still didn't work.

**Comment by Gaurav0** [comment]
Workaround: Manually change the location type in router.js to 'none'

**Comment by Gaurav0** [comment]
Fixed by #317
