### ISSUE TITLE
Write access to my gists?

### ISSUE THREAD

**Issue by fguillen** [ember-cli/ember-twiddle#323]
In order to login in this service I have to allow access to all my gists, even the private ones.. and give to the application write access to them.. meaning that:

- The application can access to my private stuff
- A bug in the application can delete all my gists

Is this necessary?

**Comment by alexspeller** [comment]
Yes, this is necessary to write to gists.

**Comment by alexspeller** [comment]
Additionally, you may not be aware that:

1. You can use twiddle without logging in at all, you just won't be able to save anything
2. If you really don't want to allow gist permission with oauth but you want to share a twiddle, you can construct your own public gist and ember twiddle will load it if you go to `https://ember-twiddle.com/<gist id>`. Here is an example: https://gist.github.com/alexspeller/dd0006ff76105e048393 - essentially provide a twiddle.json and replace slashes with dots in file paths.

**Comment by fguillen** [comment]
Thanks for the clarifications @alexspeller, I really like the ember-twiddle service.. 

I just think the required rights are a bit aggressive, specially for the "private" gists. But I don't know which level of granularity the OAuth github implementation allows you.

Best

**Comment by alexspeller** [comment]
[There is no granularity at all in the gist api](https://developer.github.com/v3/oauth/#scopes)
