### ISSUE TITLE
Implement hbs for ember-twiddle

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-twiddle#326]
@pangratz description of hbs: https://github.com/switchfly/ember-test-helpers/pull/38#issuecomment-98963675

See https://canary.ember-twiddle.com/4913a319b3647c2c696d?openFiles=tests.integration.better-checkbox-test.js%2Cbetter-checkbox.component.js

**Comment by Gaurav0** [comment]
Fixed by #337

**Comment by Gaurav0** [comment]
So this didn't work in canary. I tracked down the issue and there is a bug in minification. Disabled the minification of assets/vendor.js in canary for now. Help wanted.

**Comment by Gaurav0** [comment]
To reproduce:

1) git pull/clone master branch
2) Edit ember-cli-build not to exclude assets/vendor.js from minification
3) Disable fingerprinting in production (or prepending of domain) so production env works locally
4) ember server --environment=production

**Comment by Gaurav0** [comment]
This is the error:

TypeError: application/template.hbs: The plugin function (t){var r=t.types,n=function(t,r){var n="Ember.HTMLBars.template("+e(r)+")";return t.replaceWithSourceString?void t.replaceWithSourceString(n):n};return new t.Transformer("htmlbars-inline-precompile",{ImportDeclaration:function(e,t,n,i){if(r.isLiteral(e.source,{value:"htmlbars-inline-precompile"})){var a=e.specifiers&&e.specifiers[0];if(!r.isImportDefaultSpecifier(a)){var o=i.code,s=o.slice(e.start,e.end),l="Only `import hbs from 'htmlbars-inline-precompile'` is supported. You used: `"+s+"`";throw i.errorWithNode(e,l)}i.importSpecifier=a.local.name,"function"==typeof this.dangerouslyRemove?this.dangerouslyRemove():this.remove()}},CallExpression:function(e,t,i,a){if(r.isIdentifier(e.callee,{name:a.importSpecifier})){var o="hbs should be invoked with a single argument: the template string";if(1!==e.arguments.length)throw a.errorWithNode(e,o);var s=e.arguments[0].value;if("string"!=typeof s)throw a.errorWithNode(e,o);return n(this,s)}},TaggedTemplateExpression:function(e,t,i,a){if(r.isIdentifier(e.tag,{name:a.importSpecifier})){if(e.quasi.expressions.length)throw a.errorWithNode(e,"placeholders inside a tagged template string are not supported");var o=e.quasi.quasis.map(function(e){return e.value.cooked}).join("");return n(this,o)}}})} didn't export a Plugin instance

**Comment by Gaurav0** [comment]
Turning off name mangling in uglify also fixes the issue. To do so, use
```
minifyJS: {
      enabled: isProductionLikeBuild,
      options: {
        mangle: false
      }
    },
```

**Comment by Gaurav0** [comment]
Issue was with Babel requiring constructor.name === "Plugin" but the Plugin class constructor function's name was mangled by Uglify. Fixed by treating 'Plugin' as reserved word during minification.

**Comment by pangratz** [comment]
> Issue was with Babel requiring constructor.name === "Plugin" but the Plugin class constructor function's name was mangled by Uglify. Fixed by treating 'Plugin' as reserved word during minification.

wow, awesome detective work @Gaurav0 :mag:

**Comment by Gaurav0** [comment]
@pangratz Now should I report it as a bug to Babel or Uglify or both?

**Comment by pangratz** [comment]
I think this is an uglify issue

**Comment by Gaurav0** [comment]
@pangratz Reported
