### ISSUE TITLE
Specific error message for fail to save gist when fresh file is empty.

### ISSUE THREAD

**Issue by sheriffderek** [ember-cli/ember-twiddle#338]
I'm checking back in with twiddle and building out a mini site as a base to work with. I've been trying to build a basic 3 route page, for the last hour or two. I've written it out a few times but at the end, when I try to save, I get this error.

"Something went wrong. The gist was not saved."

I built it over again step by step and the same thing happened. _I'm stupid_, so I did it a 3rd time. The only thing I could think of, is that when I added my third route, I also added a template for that route – and there was no code in there. I added a single character, and it then saved properly. I'm sure it's more on the Gist end of things, and that it doesn't let you save _nothing_. 

Maybe templates are the only file that doesn't come with some code in place.

I could see this scaring people off for sure. A unique message would be helpful. "Could not save empty file to gist." or something along those lines. Another fix would be to just spit out an {{outlet}} in the template blue-print I guess.

**Comment by Gaurav0** [comment]
@sheriffderek Thank you very much for all of your direct and honest feedback.

**Comment by allthesignals** [comment]
I'm seeing this error when I save a Twiddle to gist after saving successfully once (the network response):

```
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Gist",
      "code": "custom",
      "field": "contents",
      "message": "contents must have unique filenames"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/gists/#edit-a-gist"
}
```

**Comment by Gaurav0** [comment]
Please try on canary and see if it has been fixed.

**Comment by allthesignals** [comment]
@Gaurav0 that seems to fix it. Thank you for the prompt reply!

**Comment by lr2120** [comment]
I am having the same issue getting this message when I try to save:
The contents of a file is completely empty, so the gist could not be saved.

I added templates and routes..

**Comment by Gaurav0** [comment]
@lr2120 There were no files that were empty? If so, please add steps to reproduce and open a new issue, that is different than this issue.
