### ISSUE TITLE
Component hbs and js should open simultaneously

### ISSUE THREAD

**Issue by joostdevries** [ember-cli/ember-twiddle#35]

**Comment by piotrpalek** [comment]
@joostdevries I was going to implement this, but I have some questions regarding this.
- should the seperate entries for creating only the component hbs or only the component js really be removed? I mean some people might want to create only a template or js file for the component
- as I understand it after creating the files the dropdown menu (for selecting files) works normally, it shows the seperate js and hbs file for selection (not a single selection which will open both files at once)
- how would you like to handle the file path selection? just open the prompt 2x ?

**Comment by piotrpalek** [comment]
For the 3rd question, I was thinking about letting people only edit part of the path, so if they write `some-component` in the prompt, it would generate `components/some-component.js` and `templates/components/some-component.hbs` files. Less possible to shoot yourself in the foot, but could be too limiting (if twiddle wants to support pod structure simultaneous to the "classic" structure, like cli works).
Could be fine for now though if pod support isn't an issue? Maybe later if pod support is required this can be rethinked and modified.

**Comment by joostdevries** [comment]
@piotrpalek I'd add an option to the file menu called `Create component` which just opens a prompt asking for the component name (instead of path). If people accidentally do enter an extension, just strip it.

I'd leave the separate options in as well.

**Comment by Gaurav0** [comment]
Fixed by #148
