### ISSUE TITLE
Can't add property default, object is not extensible

### ISSUE THREAD

**Issue by epyx25** [ember-cli/ember-twiddle#353]
Error occurs when I try to import a mixin (rollback) :
https://ember-twiddle.com/0906a584e134dc556350?openFiles=models.player.js%2C

Without the line

`import Rollback from '../mixins/rollback';`

it works fine

**Comment by Gaurav0** [comment]
Hmmm...

So apparently the mixin object is frozen / sealed, because cloning appears to 'fix' the problem: https://ember-twiddle.com/ca7e7083391a401d4e50?openFiles=mixins.rollback.js%2C

I think this is a bug in loader.js if it cannot handle a frozen / sealed object. @rwjblue @stefanpenner Is this correct?

**Comment by epyx25** [comment]
@Gaurav0  thanks! Your fix get rid of the error, but does not seem to work: 
https://ember-twiddle.com/799e6f56154c60414c98?openFiles=mixins.rollback.js%2C

I use the mixin in the models, but it does not add the `rollback` function to it. At least if I try to call it on a model instance, I am getting:

> Uncaught TypeError: club.rollback is not a function

https://gist.github.com/epyx25/799e6f56154c60414c98#file-index-controller-js-L11

p.s.: with components it works: https://ember-twiddle.com/47bfc4020af5fb720d70?openFiles=shopping-list.component.js%2C
_(ember twiddle is taken from this article: https://www.netguru.co/blog/how-to-avoid-shared-states-between-mixins-in-ember.js?utm_campaign=Blog%20Posts&utm_medium=social&utm_source=reddit)_

**Comment by Gaurav0** [comment]
@epyx25 Yes, that is why I called it a 'fix'.

**Comment by Gaurav0** [comment]
Fixed by #354

**Comment by stefanpenner** [comment]
:+1:
