### ISSUE TITLE
ember-twiddle reload page when clicking "Add..." in the menu

### ISSUE THREAD

**Issue by HenryVonfire** [ember-cli/ember-twiddle#363]
How to reproduce this issue:
- Click on one file in the tree view (with folders works fine)
- Go to the File menu and click "Add..."

It shouldn't do anything but instead of that, it reloads the page, losing whatever unsaved you were doing.

Tested in Firefox and Chromium. Same behaviour in them.

**Comment by Gaurav0** [comment]
Fixed by #364
