### ISSUE TITLE
Strange Safari Issue

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-twiddle#368]
I haven't dug in, but was supprised when navigating to [this link](https://ember-twiddle.com/59c278f6969feef685bc?openFiles=application.template.hbs] in safari (not logged in) yielded the default app, but when visiting that url in chrome it was the correct gist.

**Comment by stefanpenner** [comment]
maybe related console errors:
```
triggervendor-925c764c63ca538811ee79f8697b5be8.js:18:21954Error while parsing the 'sandbox' attribute: 'allow-modals' is an invalid sandbox flag.
ghostery-min.js:8:10044Sandbox access violation: Blocked a frame at "null" from accessing a frame at "https://ember-twiddle.com".  The frame requesting access is sandboxed and lacks the "allow-same-origin" flag.
https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.4.3/ember-template-compiler.mapFailed to load resource: the server responded with a status of 404 (HTTP/2.0 404)
```

**Comment by stefanpenner** [comment]
> triggervendor-925c764c63ca538811ee79f8697b5be8.js:18:21954Error while parsing the 'sandbox' attribute: 'allow-modals' is an invalid sandbox flag.

looks suspicious

**Comment by Gaurav0** [comment]
It seems https://github.com/ember-cli/ember-twiddle/issues/274 has come back. As before, the workaround is to insert a `#`

**Comment by Gaurav0** [comment]
cc/ @joostdevries

**Comment by davidpett** [comment]
I see this in mobile safari, does it not work on desktop either?

**Comment by Gaurav0** [comment]
Yes, not working for me on desktop either.

**Comment by joostdevries** [comment]
For some unknown reason the settings were reverted. Maybe this happens during deploys. I've fixed it manually.
