### ISSUE TITLE
Why twiddle not use JSONAPI default?

### ISSUE THREAD

**Issue by villander** [ember-cli/ember-twiddle#369]
I can't use JSONAPI with twiddle. Just plain object

**Comment by Gaurav0** [comment]
Sorry you are having difficulty. JSON API should work. Do you have a non-working twiddle link to share with me?

**Comment by pangratz** [comment]
JSON-API is used by default, see [this twiddle](https://ember-twiddle.com/0e1a24aabb8fa7c1fdd8). @villander can you provide a sample twiddle which demonstrates the issue you're having?

**Comment by villander** [comment]
@Gaurav0 look my twiddle: https://ember-twiddle.com/e1b58a65b686bb2654a7?openFiles=initializers.pretender.js%2C

@pangratz you configuration is very hard, ember twiddle must work with a adapter default `JSONAPIAdapter`? Look my twiddle too

**Comment by pangratz** [comment]
`ember-data` uses the `JSONAPIAdapter` by default; in the twiddle I posted the server is simulated using [pretender](https://github.com/pretenderjs/pretender). The response in `application/route.js` is a `JSON-API` document and the corresponding template shows the data.

In your twiddle I don't see any interaction with the store, the `model()` hook in your `routes/application.js` returns a plain JS array...

**Comment by alexspeller** [comment]
I don't think this is actually an issue. Please give more details if it is and I will reopen.

**Comment by villander** [comment]
Thanks for explanation @pangratz i understand now.
I thought the model `hook` was already an interaction with ember-data, even hard code
