### ISSUE TITLE
My Twiddle retrieval only gets 100 most recent gists globally, instead of user's gists

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-twiddle#370]
api call should be: https://api.github.com/users/NullVoxPopuli/gists

rather than:

https://api.github.com/gists?per_page=100

**Comment by Gaurav0** [comment]
Definitely worth a try. Thanks.

**Comment by Gaurav0** [comment]
Didn't work. Returned a maximum of 30 gists.
