### ISSUE TITLE
Responsive Header needs design love

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-twiddle#377]

**Comment by davidpett** [comment]
I just submitted a PR: https://github.com/ember-cli/ember-twiddle/pull/378

**Comment by Gaurav0** [comment]
<img width="532" src="https://cloud.githubusercontent.com/assets/313960/14245319/930cbfd6-fa2e-11e5-9498-564f38f8b1d1.png">

should really look more like:

<img width="386" alt="capture" src="https://cloud.githubusercontent.com/assets/313960/14245445/5bea6b42-fa2f-11e5-92c7-06f04e884801.PNG">

**Comment by davidpett** [comment]
is the header the only place that is using bootstrap? i will redo the dom without it, that is what causes some of the problems here

**Comment by Gaurav0** [comment]
I think so.

**Comment by Gaurav0** [comment]
I've heard the Ember Guides repo already has some sort of component written.

**Comment by davidpett** [comment]
The big difference is the dropdowns on twiddle that don't exist in the guides nav

**Comment by acorncom** [comment]
Paging @ryanlabouve ;-)
