### ISSUE TITLE
Addon support

### ISSUE THREAD

**Issue by joostdevries** [ember-cli/ember-twiddle#395]
- [x] Stabilize addon API
- [x] Nice addon loading indicator
- [x] Auto reload/refresh after addon build completes
- [x] Handle addon build errors
- [x] Handle addon config in twiddle.json
- [ ] Handle multiple ember / ember-template-compiler versions

**Comment by TameBadger** [comment]
Any thought regarding docs or usage instructions so far ? Wondering how to use addons now myself :D

**Comment by Gaurav0** [comment]
Once addons are supported properly, we will add a section in twiddle.json.

**Comment by joostdevries** [comment]
@Gaurav0 I've began moving everything to the new architecture.

Base URL's for API:
- Canary: https://emw2ujz4u1.execute-api.us-east-1.amazonaws.com/canary
- Production: https://howq105a2c.execute-api.us-east-1.amazonaws.com/production

**Comment by joostdevries** [comment]
I expect to finish the migration tonight/tomorrow (Dutch time).

**Comment by joostdevries** [comment]
Discovered a new issue: Alpine Linux support is not present for node-sass, https://github.com/sass/node-sass/issues/1589

**Comment by joostdevries** [comment]
We now fully support addons for 2.6 and 1.13 in Ember Twiddle canary (https://canary.ember-twiddle.com). Docs on adding more versions at https://github.com/joostdevries/twiddle-backend

**Comment by acorncom** [comment]
:+1:

**Comment by alexspeller** [comment]
This is awesome!

**Comment by ritesh83** [comment]
@joostdevries I created a twiddle with ember-cli-jstree addon but its throwing a security error.
Could you take a look? Maybe I'm doing something wrong
https://ember-twiddle.com/82809a6f7b4570b4de8416260fbb59db

**Comment by joostdevries** [comment]
@ritesh83 This is unrelated to addon support. The script tries to load a WebWorker which afaik is not enabled in sandbox mode.
