### ISSUE TITLE
Install errors on Windows

### ISSUE THREAD

**Issue by broerse** [ember-cli/ember-twiddle#4]
I get this errors installing twiddle on windows.

```
C:\dev>git clone https://github.com/alexspeller/ember-twiddle.git
Cloning into 'ember-twiddle'...
remote: Counting objects: 338, done.
Receiving object 0 (delta 0), pack-reused 338
Receiving objects: 100% (338/338), 45.57 KiB | 0 bytes/s, done.
Resolving deltas: 100% (167/167), done.
Checking connectivity... done.

C:\dev>cd ember-twiddle

C:\dev\ember-twiddle>npm install
npm WARN optional dep failed, continuing fsevents@0.3.6
-
> node-sass@1.0.3 install C:\dev\ember-twiddle\node_modules\broccoli-sass\node_m
odules\node-sass
> node build.js

child_process: customFds option is deprecated, use stdio instead.

C:\dev\ember-twiddle\node_modules\broccoli-sass\node_modules\node-sass>node "C:\
Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-
gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dev\ember-twiddle\node_modules\broccoli-sass\node_modules\node-s
ass
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.0.3 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.0.3 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\ember-twiddle\npm-debug.log

C:\dev\ember-twiddle>
```

**Comment by joostdevries** [comment]
@broerse this looks like a problem with node sass:
> Compiling versions 0.9.4 and above on Windows machines requires Visual Studio 2013 WD. If you have multiple VS versions, use npm install with the --msvs_version=2013 flag also use this flag when rebuilding the module with node-gyp or nw-gyp.

**Comment by broerse** [comment]
@joostdevries it seems you must also install an old Python version to get this to work. 

 * On Windows you need:
    * [Python][windows-python] ([`v2.7.3`][windows-python-v2.7.3] recommended, `v3.x.x` is __*not*__ supported)
    * Windows XP/Vista/7:
      * Microsoft Visual Studio C++ 2010 ([Express][msvc2010] version works well)
      * For 64-bit builds of node and native modules you will _**also**_ need the [Windows 7 64-bit SDK][win7sdk]
        * If the install fails, try uninstalling any C++ 2010 x64&x86 Redistributable that you have installed first.
      * If you get errors that the 64-bit compilers are not installed you may also need the [compiler update for the Windows SDK 7.1]
    * Windows 7/8:
      * Microsoft Visual Studio C++ 2012/13 for Windows Desktop ([Express][msvc2012] version works well)

This is not good for windows users. Is there no msi installer for node sass?

**Comment by broerse** [comment]
@joostdevries I found that if you run `npm install node-sass` it install's the binaries fine. But the above `npm install' still fails.

**Comment by joostdevries** [comment]
@broerse with the same error?

**Comment by broerse** [comment]
@joostdevries Yes with the same error. Perhaps twiddle expects an older version of note-sass and tries to recompile. I will check this later.

**Comment by broerse** [comment]
@joostdevries The error is in `"broccoli-sass": "git://github.com/ef4/broccoli-sass"` 
Can we use the normal broccoli-sass??

**Comment by broerse** [comment]
@joostdevries If I write `"broccoli-sass": "0.6.6"` I can install but get two hint errors. Twiddle seems to work.

```
gist/controller.js: line 2, col 8, 'File' is defined but never used.

1 error

lib/file.js: line 3, col 8, 'Gist' is defined but never used.

1 error

===== 2 JSHint Errors
```

**Comment by joostdevries** [comment]
@broerse cool. Just a heads up: I'll be changing a lot before tuesday ;-)

**Comment by joostdevries** [comment]
@broerse Could you check whether this is still an issue?

**Comment by broerse** [comment]
@joostdevries I will check tomorrow.

**Comment by broerse** [comment]
@joostdevries It installs and works without Python on Windows 10. I only get this warning:

```
DEPRECATION: `ember-cli/lib/errors/silent.js` is deprecated, use `silent-error` instead.
version: 1.13.1
bootstrap-sassy config:  some JS loaded [dropdown], glphicons enabled
[Deprecated] this.mergeTrees is deprecated, please use broccoli-merge-trees directly instead  [addon: ember-cli-file-creator]
```

**Comment by joostdevries** [comment]
:+1:
