### ISSUE TITLE
File does not get deleted

### ISSUE THREAD

**Issue by locks** [ember-cli/ember-twiddle#401]
## Reproduction steps
- Visit https://ember-twiddle.com/248ff8e9332f02fcbd45
- Select `template.hbs` under the `application-loading` folder
- Select "Delete application-loading/template.hbs" from the `File` menu

## Expected results
- File gets deleted
- Sidebar gets refreshed

## Actual results
- File does not get deleted. You can confirm by seeing the loading template on app reload
- Sidebar does not get refreshed

**Comment by Gaurav0** [comment]
@locks Can you check if your issue is solved: https://canary.ember-twiddle.com/248ff8e9332f02fcbd45

**Comment by locks** [comment]
@Gaurav0 perfect :ok_hand:
