### ISSUE TITLE
Change app name `demo-app` to `twiddle` in a backwards-compatible way

### ISSUE THREAD

**Issue by joostdevries** [ember-cli/ember-twiddle#41]
Detect twiddle version and use either `demo-app` or `twiddle`.

--- 

2016-04-12

The app name was changed but ideally we make this backwards compatible. This requires:
- [ ] The addon-builder to use variable app names
- [ ] The UI to use variable app names

**Comment by Gaurav0** [comment]
It would be even better if the user could specify.

**Comment by joostdevries** [comment]
true. Maybe parse a minimal version package.json

**Comment by joostdevries** [comment]
this sounds like a relatively simple thing now we have twiddle.json

**Comment by leomeira** [comment]
Hey Gaurav, I would like to work on this issue.

**Comment by Gaurav0** [comment]
@leomeira Thanks!

**Comment by joostdevries** [comment]
I'd be careful with this considering the fact that addons actually need to know the app name so making it variable is probably not a good idea (or we'd have to write a custom resolver...)

**Comment by Gaurav0** [comment]
Addons that rely on knowing the app name except via modulePrefix are buggy.

**Comment by joostdevries** [comment]
@Gaurav0 that may be but during the build process anything in the `app` directory of an addon is namespaced to the app name. If we want #349 to work we need a consistent app (module) name.

**Comment by Gaurav0** [comment]
I see. In that case let's agree on `app` and keep it simple?

**Comment by leomeira** [comment]
:+1:

**Comment by joostdevries** [comment]
The app name was changed but ideally we make this backwards compatible. This required
- [ ] The addon-builder to use variable app names
- [ ] The UI to use variable app names

**Comment by joostdevries** [comment]
We may also choose NOT to do this, based on:

https://github.com/ember-cli/ember-twiddle/pull/394#issuecomment-208912214

> It doesn't break imports that use relative urls. We never made 'demo-app' name public.

**Comment by joostdevries** [comment]
closed by #396
