### ISSUE TITLE
Warning that author has updated Twiddle

### ISSUE THREAD

**Issue by locks** [ember-cli/ember-twiddle#414]
It would be cool if Twiddle would warn viewers if the author has updated the original Twiddle, so the viewer can refresh and get the goodiness.

**Comment by alexspeller** [comment]
Does the gist api have webhooks to support this?

**Comment by alexspeller** [comment]
polling is a no-go due to rate limiting

**Comment by Gaurav0** [comment]
@alexspeller No webhooks are available for gists.

**Comment by locks** [comment]
But twiddle knows when a user saves their twiddle, right? Could that trigger a webhook?

**Comment by joostdevries** [comment]
this would require a more complex backend than we currently have. While I agree that it'd be nice, I don't think this is something that can be done on the sort term.
