### ISSUE TITLE
Don't hide reload button

### ISSUE THREAD

**Issue by locks** [ember-cli/ember-twiddle#415]
How does the team feel about not hiding the reload button when live reload is selected? Sometimes I want to trigger a reload without having modified the code, and I have to deselect live reload to do it, or pointlessly edit the code.

**Comment by alexspeller** [comment]
👍 I hit this surprisingly often

**Comment by Gaurav0** [comment]
What is the use case for this?

**Comment by sheriffderek** [comment]
I do this as well, but it more of a sanity check. As cool as CodePen and JSfiddle sandboxes are, they sometimes glitch and I just want to reload to be sure. That being said, if I could be sure that it's not the app - I would really enjoy not second guessing what the problem may be.
