### ISSUE TITLE
If power select is first input in liquid-fire modal page freezes

### ISSUE THREAD

**Issue by mukk85** [ember-cli/ember-twiddle#418]
It seems to be in an infinite loop in the focus function. I have worked around it by adding an input in a hidden div before it. I also ran into a case where I could not get the search field focused when inside the modal, but do not have a way to reliably reproduce.

**Comment by alexspeller** [comment]
Is this issue filed in the right project? Is it ember-twiddle specific? Can you share a reproduction case?

**Comment by Gaurav0** [comment]
Could you please provide twiddle link?

**Comment by mukk85** [comment]
Wrong project sorry.
