### ISSUE TITLE
[feature request] Provide alternate saving options

### ISSUE THREAD

**Issue by crodriguez1a** [ember-cli/ember-twiddle#433]
Provide alternate saving options for users without access to Github (eg, firewall, proxy). Maybe there could be a downloadable zip containing the file directory structure and files?

**Comment by sheriffderek** [comment]
@crodriguez1a I think you should amend the issue title to clearly describe what you mean about Github. On first glance, this looks like it may be a UI issue(to me). I'd offer you some wording, but I'm not sure how to best say it either.

**Comment by Gaurav0** [comment]
A download zip option has been added thanks to @nummi
