### ISSUE TITLE
Template changes not taking effect

### ISSUE THREAD

**Issue by ef4** [ember-cli/ember-twiddle#448]
1. Start a new twiddle.
2. Edit the application.hbs template.
3. The app reloads, but the template change is not reflected in the output.

This applies on both https://canary.ember-twiddle.com and https://ember-twiddle.com

Chrome 51.0.2704.84 (64-bit)

Screencast: https://monosnap.com/file/GU9uW3Svyy8lof0wykKHiszrbarZgP

**Comment by alexspeller** [comment]
That's unusual, can confirm I'm seeing this too

**Comment by alexspeller** [comment]
Also, updating application.js seems to not have any effect for me either

**Comment by Gaurav0** [comment]
Thanks guys. In order to avoid getting such serious bugs into production, please occasionally use and test canary.

**Comment by Gaurav0** [comment]
@ef4 Please verify this is fixed on canary
