### ISSUE TITLE
ember-browserify support?

### ISSUE THREAD

**Issue by toranb** [ember-cli/ember-twiddle#459]
Today I learned about addons getting support and tried using ember-browserify w/ redux but I seem to get an import error. I wanted to see if you could spin up a twiddle using these 2 deps

```
    "ember-browserify": "^1.1.8",
    "redux": "^3.4.0"
```

and do something basic in the twiddle like so

```js
import Redux from 'npm:redux';
var { createStore } = Redux;
```

I use this heavily in my addon "ember-redux" and wanted to see when you thought browserify would be supported by twiddle. Thank you so much for supporting such a great project !!!

**Comment by Gaurav0** [comment]
@toranb Can you give us a non-working twiddle?

**Comment by toranb** [comment]
https://ember-twiddle.com/c2a23b04ed2521c7485a99a9188d3175

I'm almost certain the issue is that redux is not an addon but when combined w/ ember-browserify I'm allowed to use it ES6 style in my ember apps/or ember addons.

I'm unsure if this can be support at this time - mostly just wanted to open an issue to mention it :)

@Gaurav0 thanks for improving ember-twiddle like a boss :)

**Comment by Gaurav0** [comment]
@toranb So, yes redux is not an addon, and cannot be added to the addons hash.

At this time we do not support npm package dependencies. For now, just use:

`https://cdnjs.cloudflare.com/ajax/libs/redux/3.0.4/redux.js`

in your dependencies instead of `ember-browserify` and `redux`.

An alternative workaround is using a 'wrapper' addon that will include the `redux` package using the `addPackageToProject` api.

**Comment by joostdevries** [comment]
@toranb I'd say that the solution @Gaurav0 proposed of using a 'wrapper-addon' makes the most sense. I don't see it happening that we support 'browserifying' any NPM package.

**Comment by toranb** [comment]
@joostdevries @Gaurav0 sounds like a plan! Thank you both!

**Comment by toranb** [comment]
Just a heads up for anyone w/ an addon like this - the commit below made this 100% twiddle compatible (even w/ redux and browserify as requirements)

https://github.com/toranb/ember-redux/commit/61bbfa4895fcb8ae43f7f317a0959dd3ee6d462e
