### ISSUE TITLE
Does the app support bower components in the `twiddle.json` `dependencies` property?

### ISSUE THREAD

**Issue by marclundgren** [ember-cli/ember-twiddle#464]
Hi, 

After reading the [Basic usage instructions](https://github.com/ember-cli/ember-twiddle/issues/108), I was hoping to learn if bower.json components are supported or not (seems like not).

For example, I'm trying to include a component for ace-editor. After adding 

```
"ace-builds": "1.1.8",
```

to twiddle.json's `dependencies` property, I don't see any errors in the console output, or the UI. If I try to refresh the page to confirm whether or not my new property was saved, I see it wasn't saved :(

We might want better error handling for unsupported twiddle.json props/values.

**Comment by Gaurav0** [comment]
At this time bower components and npm packages are only supported if a "wrapper" addon is created that brings those components in as part of its build process.

While the ember-browserify addon builds and works with ember-twiddle, there is no place currently to specify npm dependencies.

Any way to specify bower dependencies would require several pieces of information:
1. bower dependency name
2. bower dependency version
3. array containing paths to files in bower components that should be imported into the app.
This is a limitation of bower.

@stefanpenner Is the effort to deprecate bower still under way in ember-cli?

@marclundgren I would strongly suggest using a CDN in place of bower dependencies in ember-twiddle. Even if we could get it working, a CDN would be much faster than using bower. Ace Editor is available from https://www.jsdelivr.com/projects/ace

**Comment by marclundgren** [comment]
> I would strongly suggest using a CDN in place of bower dependencies in ember-twiddle. Even if we could get it working, a CDN would be much faster than using bower. Ace Editor is available from https://www.jsdelivr.com/projects/ace

thanks @Gaurav0. This (almost) worked for me. I'm seeing an ace error during runtime, but that's not an ember-twiddle problem.
