### ISSUE TITLE
External assets

### ISSUE THREAD

**Issue by vjrngn** [ember-cli/ember-twiddle#466]
Hey guys,

First of all, awesome work on ember-twiddle! Really love it. 

I was wondering if you include a mechanism to import external assets (css/js) from cdns. That'll definitely be a nice feature to have.

**Comment by alexspeller** [comment]
yes, you can include assets and also addons in `twiddle.json`

**Comment by sheriffderek** [comment]
This is a good example for why we need a how-to / "What ember-twiddle is" and "how to use it" pages. Nothing in the help section really tells you the secrets of how this works.

**Comment by vjrngn** [comment]
Thanks @alexspeller. I agree @sheriffderek

**Comment by sheriffderek** [comment]
I'm still wondering why we don't have any 'how to' or 'about' page on twiddle that describes how to do things like this. It still feels like a 'cool kids' club in many ways. When addressing StackOverflow questions, I often encourage people to build out twiddles of their addon issue ~ but it is unlikely that they will be able to figure out how to include add-ons if they aren't very familiar with twiddle already.  I'll open an issue for a path for such a page.
