### ISSUE TITLE
How to add addon in twiddle

### ISSUE THREAD

**Issue by abrahamspaa** [ember-cli/ember-twiddle#471]
Cannot able to add ember-addon in ember twiddle,  throwing an error `undefined`. 

Example: 
https://ember-twiddle.com/2e49477a911ac32efa15e260c0a9771f?openFiles=templates.application.hbs%2C

Do I missing anything here?

**Comment by Gaurav0** [comment]
https://ember-twiddle.com/26b07943f1cedf77912bc18869629570?openFiles=twiddle.json%2C

Unfortunately, support for addons in Ember 2.7.0 has not yet been added. See https://github.com/joostdevries/twiddle-backend/pull/8 cc/ @joostdevries

**Comment by abrahamspaa** [comment]
Thank you @Gaurav0, closing this issues.
