### ISSUE TITLE
Addons not working with Ember 2.7

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-twiddle#472]
cc/ @joostdevries You have to use Ember 2.6 for now.

**Comment by ykaragol** [comment]
An error raised "undefined" while an addon added to the twiddle.json at ember 2.7. [Discussed at SO question](http://stackoverflow.com/questions/38737150/how-to-create-ember-twiddle-demo-with-addons)

**Comment by urbany** [comment]
It's not working for 2.8.0 either.

**Comment by sheriffderek** [comment]
If there was an 'about' page with a 'road-map' and a 'status' for certain features like this, fewer issues like this would get opened.

**Comment by Gaurav0** [comment]
@joostdevries hasn't given me access or instructions to fix this myself.

**Comment by Gaurav0** [comment]
Fixed!
