### ISSUE TITLE
visual: "Run Test" and "Live Reload" overlap

### ISSUE THREAD

**Issue by machty** [ember-cli/ember-twiddle#484]
![image](https://cloud.githubusercontent.com/assets/81818/19313152/84c0a020-9063-11e6-8700-f6ba6b675cbc.png)

Seeing this on Chrome 53.0.2785.143 (64-bit) (mac)

**Comment by Gaurav0** [comment]
Fixed on canary.

![screen shot 2016-10-12 at 10 07 01 am](https://cloud.githubusercontent.com/assets/313960/19319882/cef7658e-9063-11e6-8f1d-f3ea84024e25.png)
