### ISSUE TITLE
Unable to install ember-font-awesome

### ISSUE THREAD

**Issue by kybishop** [ember-cli/ember-twiddle#496]
https://ember-twiddle.com/7edbcea7b2961e50cbdee79703b3fd28?openFiles=templates.application.hbs%2C

Screenshot incase anyone sees a "works on my machine"
![screen shot 2016-11-27 at 8 20 30 pm](https://cloud.githubusercontent.com/assets/679465/20648657/70ba6926-b4df-11e6-8884-cf441b6e85fc.png)

**Comment by Gaurav0** [comment]
Looks like an issue with the addon. headerFiles cannot be a glob." Please if it check it builds locally with a fresh install using node 0.12

**Comment by kybishop** [comment]
Downgraded to node v0.12.0 via (n)[https://github.com/tj/n].

Switched to a local project which uses ember-font-awesome and ran `npm cache clean && bower cache clean && rm -rf node_modules bower_components dist tmp`. `ember s` runs without a hitch.

**Comment by kybishop** [comment]
@Gaurav0 loading the twiddle again gave me a much more informative stacktrace (hurray deterministic computer programs /s :wink:)

It looks like the error is from lack of a python executable, as tracked down to the addon's `ember-cli-sass` dependency.

Given how popular something like `ember-cli-sass` is, do you have any thoughts on adding python2 support to ember-twiddle? If it is already available, how might I be able to patch the addon to use it?

```
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (/addon-builder/node_modules/ember-cli-font-awesome/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/node_modules/node-gyp/lib/configure.js:449:14)
gyp ERR! stack     at /addon-builder/node_modules/ember-cli-font-awesome/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/node_modules/node-gyp/lib/configure.js:353:11
gyp ERR! stack     at F (/addon-builder/node_modules/which/which.js:69:16)
gyp ERR! stack     at E (/addon-builder/node_modules/which/which.js:81:29)
gyp ERR! stack     at /addon-builder/node_modules/which/which.js:90:16
gyp ERR! stack     at /addon-builder/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /addon-builder/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.4.10-22.54.amzn1.x86_64
gyp ERR! command "/usr/bin/node" "/addon-builder/node_modules/ember-cli-font-awesome/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /addon-builder/node_modules/ember-cli-font-awesome/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass
gyp ERR! node -v v5.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
Build failed with error code: 1
```

**Comment by kybishop** [comment]
Just discovered issue #483. Closing this in favor of that issue.
