### ISSUE TITLE
addon config is not merged in app config

### ISSUE THREAD

**Issue by jelhan** [ember-cli/ember-twiddle#499]
Configuration provided by an addon is not merged into app config. I discovered this with [ember-cli-mirage](https://github.com/samselikoff/ember-cli-mirage). Of course adding needed configuration to `ENV` section in `twiddle.json` is an easy work-a-round.

**Comment by Gaurav0** [comment]
Full config.js cannot be provided because we do not have a node environment to run it.

**Comment by jacobq** [comment]
In my case, I was able to work-around this as described here: https://github.com/yapplabs/ember-modal-dialog/issues/198
