### ISSUE TITLE
Component integration tests broken under Ember 2.10.x

### ISSUE THREAD

**Issue by omarestrella** [ember-cli/ember-twiddle#500]
Component integration tests are broken when running them in a twiddle using any version of Ember 2.10. You can see the issue [using this twiddle here](https://ember-twiddle.com/fb2369455c41b581444f4b34d92f0cf6?openFiles=tests.integration.components.my-component-test.js%2C) and by switching between Ember versions. The simple integration test will pass under 2.9.x, but fail in Ember 2.10.x.

**Comment by morhook** [comment]
Same problem detected here! The culprit lines `this.render(hbs`{{my-component}}`);` and
```
this.render(hbs`
    {{#my-component}}
      template block text
    {{/my-component}}
  `);
```

**Comment by Gaurav0** [comment]
Simplified test case: https://ember-twiddle.com/9b94c3a914d46c85001e3c90a0a63640?openFiles=tests.integration.components.my-component-test.js%2Ctemplates.components.my-component.hbs

**Comment by Gaurav0** [comment]
Verified fixed: https://canary.ember-twiddle.com/9b94c3a914d46c85001e3c90a0a63640?openFiles=tests.integration.components.my-component-test.js%2Ctemplates.components.my-component.hbs

**Comment by morhook** [comment]
Tested on https://canary.ember-twiddle.com/ and looks good! Thanks @Gaurav0
