### ISSUE TITLE
Reset a frozen addon build

### ISSUE THREAD

**Issue by samselikoff** [ember-cli/ember-twiddle#504]
Hi there!

Is it possible to reset a frozen addon build? I published a new version of Mirage and tried to use it in [this twiddle](https://ember-twiddle.com/802cd2f92e8c6c7280f42b054f393097), but it's stuck.

Thank you for all your amazing work on this tool!!

**Comment by joostdevries** [comment]
Howdy! In general I'd suggest to create an issue for the specific build that froze. The process of 'resetting a build' basically means logging into AWS and deleting the specific twiddle.json file for that build. This could be automated but in general 'hanging builds' should not be that common and usually when a build hangs, resetting won't fix the problem. 

**Right now, there's an issue with the build system that's causing issues: #505**

**Comment by joostdevries** [comment]
@samselikoff I've reset the build for you
