### ISSUE TITLE
Addons cannot be built due to lack of CPU credits (AWS)

### ISSUE THREAD

**Issue by joostdevries** [ember-cli/ember-twiddle#505]
Due to an increase in 'idle' CPU usage on the build server, the (micro) EC2 instance has run out of CPU credits. Because of this, builds are not running properly at the moment.

I'll try to track down the cause of the increas in idle CPU. In the meantime, if someone can hook us up with AWS credits (I already gave @wifelette login info to the accounts) we can upgrade the instance to not be dependent on CPU credits.

![image](https://cloud.githubusercontent.com/assets/3824616/21742439/98426be4-d4ef-11e6-9a9b-f0ccdad56da4.png)

**Comment by joostdevries** [comment]
I've terminated the current EC2 instance and started a new one to see if that helps.

**Comment by joostdevries** [comment]
The problem is fixed but I don't have the faintest clue what caused it. @Gaurav0 was there anything specific happening on dec 31?

**Comment by Gaurav0** [comment]
@joostdevries I have no idea. Nothing happened that I know of.
