### ISSUE TITLE
canary twiddle won't sign in with github

### ISSUE THREAD

**Issue by toranb** [ember-cli/ember-twiddle#509]
Today I was hacking on the canary branch and found that if I tried to sign in I got this error

![screen shot 2017-01-15 at 2 41 28 pm](https://cloud.githubusercontent.com/assets/147411/21966014/d70994be-db30-11e6-9c5f-0ced6f868337.png)

Not sure but I thought the canary build allowed authentication :) if I'm wrong just close this out and ignore me

**Comment by dustinfarris** [comment]
Confirm, GitHub sign-in on canary redirects to localhost after authenticating with GitHub, does not persist token to twiddle.

**Comment by Gaurav0** [comment]
Fixed by #511
