### ISSUE TITLE
regular twiddle won't work with inline hbs and ember 2.10

### ISSUE THREAD

**Issue by toranb** [ember-cli/ember-twiddle#510]
When using non canary twiddle today I found that if I wrote this component

```js
import Ember from 'ember';
import hbs from 'htmlbars-inline-precompile';

export default Ember.Component.extend({
  layout: hbs`
    <h1>TORAN</h1>
  `
});
```

I would get the following error

![screen shot 2017-01-15 at 2 43 47 pm](https://cloud.githubusercontent.com/assets/147411/21966027/304f84ac-db31-11e6-9885-f613a1101c93.png)

This using the default configuration that ships today w/ ember-twiddle

```js
{
  "version": "0.10.7",
  "EmberENV": {
    "FEATURES": {}
  },
  "options": {
    "use_pods": true,
    "enable-testing": false
  },
  "dependencies": {
    "jquery": "https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.js",
    "ember": "2.10.0",
    "ember-data": "2.10.0",
    "ember-template-compiler": "2.10.0",
    "ember-testing": "2.10.0"
  },
  "addons": {

  }
}
```

Thanks for the continued support of `ember-twiddle.com` - this is one killer web app!!!

**Comment by Gaurav0** [comment]
Fixed in canary. See #500

**Comment by toranb** [comment]
Awesome! Thanks again
