### ISSUE TITLE
Liquid Fire Not Working / Vendor CSS treated as JS

### ISSUE THREAD

**Issue by iezer** [ember-cli/ember-twiddle#513]
Liquid Fire is not working within Ember Twiddle. It seems that some CSS from vendor/liquid-fire.css is getting merged into the addon.js file.

Here is a reproduction:
https://ember-twiddle.com/807383f0c58810bcf2f2bb7bd269d22e?openFiles=twiddle.json%2C

Liquid Fire Issue: https://github.com/ember-animation/liquid-fire/issues/536

**Comment by Gaurav0** [comment]
Fixed in canary. See https://canary.ember-twiddle.com/807383f0c58810bcf2f2bb7bd269d22e?openFiles=twiddle.json%2C
