### ISSUE TITLE
Upgrading to ember-cli-qunit 3.0.1 breaks tests

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-twiddle#516]
Getting the error that method `stop` is undefined.

Stacktrace:

testem.js:969 TypeError: QUnit.stop is not a function
    at Class.asyncStart (VM484 ember.debug.js:37324)
    at Object.asyncStart (VM484 ember.debug.js:38454)
    at VM484 ember.debug.js:37613
    at wait-for-loaded-iframe.js:23
    at Class.andThen (ember.debug.js:37672)
    at ember.debug.js:37615
    at isolate (ember.debug.js:38744)
    at ember.debug.js:38700
    at tryCatch (ember.debug.js:58165)
    at invokeCallback (ember.debug.js:58177)

asyncStart does indeed call a method called stop still in the latest Ember.js:

https://github.com/emberjs/ember.js/blob/master/packages/ember-testing/lib/adapters/qunit.js#L15

**Comment by rwjblue** [comment]
ember-cli-qunit@3 does nto use the ember-testing qunit adapter, it has its own [here](https://github.com/emberjs/ember-qunit/blob/master/lib/ember-qunit/adapter.js)

**Comment by Gaurav0** [comment]
QUnit 2.x can no longer be run in a sandboxed iframe because of a direct reference to window.sessionStorage

**Comment by rwjblue** [comment]
Hmm, seems unintentional...

@trentmwillis - Do you happen to know if this was intentional?

**Comment by Gaurav0** [comment]
Fixed a while ago.
