### ISSUE TITLE
Addons that define environment specific asset paths for app.import() fail to build

### ISSUE THREAD

**Issue by Panman8201** [ember-cli/ember-twiddle#519]
It seems like the ember-twiddle addon build process expects only strings for `app.import()`. Addons that define [environment specific asset paths](https://ember-cli.com/user-guide/#environment-specific-assets) fail to build with a "Path must be a string." error message. A couple example addons are [`ember-font-awesome`](https://github.com/martndemus/ember-font-awesome/blob/2.2.0/index.js#L95-L98) and [`ember-cli-bootswatch`](https://github.com/Panman8201/ember-cli-bootswatch/blob/v1.13.2/index.js#L130-L133).

**Comment by Gaurav0** [comment]
Should be fixed by https://github.com/joostdevries/twiddle-backend/pull/18

I'll deploy along with the next twiddle canary.

**Comment by Panman8201** [comment]
Ha, funny we both submitted on this issue yesterday.

I look forward to trying out the fix in canary. Just let me know when to test. Thanks!

**Comment by Gaurav0** [comment]
Fix has been deployed to canary.

**Comment by Panman8201** [comment]
Is there a build cache that needs to be busted? I tried adding `"ember-font-awesome": "2.2.0"` to the `twiddle.json` addons but _quickly_ got the same build error about "Path must be a string". This was on https://canary.ember-twiddle.com/

**Comment by Gaurav0** [comment]
Sorry, deleted cache.

**Comment by Panman8201** [comment]
I'm getting some odd results. Console reports "Uncaught SyntaxError: Invalid or unexpected token" in `addon.js:1`. Looking at that file, this is what Chrome is showing;

![screen shot 2017-02-02 at 3 10 04 pm](https://cloud.githubusercontent.com/assets/3475765/22568529/bfe4f274-e959-11e6-9234-8673442b6464.png)

**Comment by Gaurav0** [comment]
That is so weird.

**Comment by Panman8201** [comment]
Interesting, I wrote some of that import logic. Is there a twiddle reason for this do you think?

https://github.com/martndemus/ember-font-awesome/blob/2.2.0/index.js#L121-L124

**Comment by Gaurav0** [comment]
Twiddle backend issue. I fixed it partially so far: https://canary.ember-twiddle.com/ff7d27da003b8244a57e3f5ec6d2420c?openFiles=twiddle.json%2C

**Comment by Gaurav0** [comment]
Partial fix deployed to production. Correctly handling assets in twiddle backend (such as fonts) still needs to be implemented.
