### ISSUE TITLE
User-definable build interval (incl. manual)

### ISSUE THREAD

**Issue by graham-sportsmgmt** [ember-cli/ember-twiddle#523]
I'd love to have the option to set how long it will take after I stop typing before the Twiddle rebuilds itself.  This freezes my browser and stops my progress momentarily.

It would be nice to have the interval set by the user for this.  I see that there's an option to turn off "Live Reload" and a manual "Run Now" button which is great.

**Comment by Gaurav0** [comment]
This would require user preferences.

**Comment by graham-sportsmgmt** [comment]
Why could it not just be another option right next to Live Reload that is set in every session?  I don't believe that it requires user preferences.

**Comment by Gaurav0** [comment]
We're trying to avoid adding additional UI. Ember Twiddle already has too much. We are simplifying it with the redesign. :)
