### ISSUE TITLE
Components with iframes won't display content due to security policy

### ISSUE THREAD

**Issue by graham-sportsmgmt** [ember-cli/ember-twiddle#524]
I am developing a set of components for the Kendo UI jquery library, and so far two components are not working in Ember Twiddle due to iframe security issues.

https://ember-twiddle.com/7fdc2dd45d2732c44571222534854e60

Select Editors... Editor or Other... Media Player to see the issue.

In Chrome, these are the two errors that are in the console:

> Sandbox access violation: Blocked a frame at "null" from accessing a frame at "null".  Both frames are sandboxed and lack the "allow-same-origin" flag.

> Uncaught DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.

In Firefox this is the error:

> Error: Permission denied to access property "document"

**Comment by Gaurav0** [comment]
Frames within the iframe cannot be allowed because of security issues.
