### ISSUE TITLE
Unable to use w/ ember-data-model-fragments

### ISSUE THREAD

**Issue by workmanw** [ember-cli/ember-twiddle#531]
Cross from: https://github.com/lytics/ember-data-model-fragments/issues/217

Here is a recently created twiddle that tries to use the ember-data-model-fragments addon. https://ember-twiddle.com/0b6d062dd744f62a97f4710f781c8acf?openFiles=templates.application.hbs%2C

The error here is:
```
Uncaught Error: Could not find module `ember-data/-private/system/model/internal-model` imported from `ember-data-model-fragments/ext`
    at missingModule (addon.js:239)
    at findModule (addon.js:250)
    at Module.findDeps (addon.js:190)
    at findModule (addon.js:253)
    at Module.findDeps (addon.js:190)
    at findModule (addon.js:253)
    at Module.findDeps (addon.js:190)
    at findModule (addon.js:253)
    at Module.findDeps (addon.js:190)
```

It seems like maybe the problem is that this package has to import private packages. But it's definitely not alone in that, many other addons rely on private packages ( https://emberobserver.com/code-search?codeQuery=-private ). 

I'd love to get this fixed, but I would know where to start.

**Comment by Gaurav0** [comment]
Have you tried making `ember-data` a dependency of your addon?

**Comment by workmanw** [comment]
@Gaurav0 Hmm, actually I haven't tried that. We discussed adding `ember-data` as dependency a while back, but we didn't end up doing so for other reasons. The twiddle.json lists `ember-data` as a dependency so that didn't occur to me. Let me try pushing a branch with `ember-data` as a dependency.

**Comment by workmanw** [comment]
@Gaurav0 So I did try to add it as a dependency and put it on a branch, but it doesn't seem like I can include code from a branch in a twiddle.json file. I guess we'd have to actually put it into a release to test it. Is that right?

----- 

I believe this is actually specific to `ember-data`. The problem seems that the addons are built in isolation from `ember` and `ember-data`. They seem to end up using a different module loader. See:

<img width="1440" alt="screen shot 2017-03-01 at 4 33 39 pm" src="https://cloud.githubusercontent.com/assets/825487/23482489/46f60868-fe9d-11e6-8a5c-604de15b7d59.png">

And ember-twiddle seems to provide it's own shims for ember-data. See: https://github.com/ember-cli/ember-twiddle/blob/master/vendor/ember-data-shims.js

Any thoughts?

**Comment by Gaurav0** [comment]
Yes, you must release to npm.

**Comment by workmanw** [comment]
@Gaurav0 Okay, I would have to confer with other maintainers of ember-data-model-fragments before publishing a release to npm that was just for testing. 

I'm a little skeptical that this will actual resolve the issue. As the second part of my previous comment showed it seems the problem is that ember-data is isolated and shimed from the rest of the packages in the addon.js build file. Even when you move `ember-data` from `dependencies` to `addons` in the `twiddle.json`, it is still not built into the `addon.js` file. 

Do you have any thoughts on this?

**Comment by workmanw** [comment]
@Gaurav0 Okay, so I forked the addon and published a new addon ([ds-mf-twiddle-test](https://www.npmjs.com/package/ds-mf-twiddle-test)).

This created a new problem because it includes two copies of ember-data. One from `dependencies` and one in the `addon.js` file (because it was now required by `ds-mf-twiddle-test`). See here:
https://ember-twiddle.com/e3561bc9fa0bab4a0d13d0ffa254f0f4?openFiles=twiddle.json%2C

```javascript
"Assertion Failed: The initializer 'data-adapter' has already been registered"
    at assert (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.10.2/ember.debug.js:5715:7)
    at Object.assert (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.10.2/ember.debug.js:16643:34)
    at Function.initializer (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.10.2/ember.debug.js:4840:19)
    at https://assets.ember-twiddle.com/assets/twiddle-deps.js?0.11.0:344:29
    at Array.forEach (native)
    at exports.default (https://assets.ember-twiddle.com/assets/twiddle-deps.js?0.11.0:328:8)
    at Module.callback (about:srcdoc:75:41)
    at Module.exports (https://addons.ember-twiddle.com/ember-2.10.1/ds-mf-twiddle-test/0.0.2/addon.js:131:32)
    at requireModule (https://addons.ember-twiddle.com/ember-2.10.1/ds-mf-twiddle-test/0.0.2/addon.js:23:18)"

```

------

So it seems like the next obvious thing is to just remove it from the `dependencies` section. However that creates an exception in the `ember-data-shims.js` file. See here: https://ember-twiddle.com/b7a93f65569e03ed014631bbe98fb086?openFiles=twiddle.json%2C

```javascript
Uncaught TypeError: Cannot read property 'Model' of undefined
    at Module.callback (twiddle-deps.js:281)
    at Module.exports (addon.js:131)
    at Module._reify (addon.js:164)
    at Module.reify (addon.js:150)
    at Module.exports (addon.js:129)
    at Module._reify (addon.js:164)
    at Module.reify (addon.js:150)
    at Module.exports (addon.js:129)
    at Module._reify (addon.js:164)
    at Module.reify (addon.js:150)
```

:(

**Comment by rwjblue** [comment]
> Even when you move ember-data from dependencies to addons in the twiddle.json, it is still not built into the addon.js file.

Agreed.  `ember-data` should be in `addons` key in `twiddle.json`.  When you do that with recent versions of ember-data we have have access to the `ember-data/-private/*` modules, but throw an error when trying to process `vendor/ember-data-shims.js` (because `window.DS` is not present).

See demo: https://ember-twiddle.com/7ba77ef120e2dcdebdd2506b425091b4?openFiles=twiddle.json%2C

**Comment by Gaurav0** [comment]
@rwjblue Cool. We have to maintain backward compatibility and so I guess we must include vendor/ember-data-shims.js conditionally, and move ember-data to the addons section if it is greater than or equal to 2.3?

**Comment by workmanw** [comment]
> We have to maintain backward compatibility and so I guess we must include vendor/ember-data-shims.js conditionally, and move ember-data to the addons section if it is greater than or equal to 2.3?

Oh man, I just realized what that actually means. Because you have to/want to support really old ember-twiddles, but running on the newest version. 

While I think making `ember-data` build as part of `addon` is 👍 and would potentially prevent issues with other addons, I really hate to add a bunch of work and headache for something that might have dimensioning returns. 

If we just wanted to fix this particular issue, we might be able to do so by adding the `-private` imports to the `ember-data-shims.js` file. I'd be happy to explore that path (I assume most of the necessary classes are available on the `DS` namespace).

**Comment by rwjblue** [comment]
We can make our ember-data shims smarter, to avoid going boom when using ember-data as an addon. Then we can update our default twiddle.json to move ember-data down into addons. Both changes should be backwards compat AFAICT, right @gaurav0?

**Comment by Gaurav0** [comment]
Trying this out in the PR above.
