### ISSUE TITLE
Ember Data 2.12.0 published to cdnjs.com is broken.

### ISSUE THREAD

**Issue by danielspaniel** [ember-cli/ember-twiddle#534]
Is it automatic that the "release" will point to new release of ember/ember-data?
 Currently it seems not. 
The release version of ember-data is still pointing to 2.11.3, when the current release is 2.12.0 
 Not sure if I just have to wait another week or if it is a code issue?

**Comment by Gaurav0** [comment]
It is not a code issue. The release branch has not been updated on builds.emberjs.com.

**Comment by Gaurav0** [comment]
Reopening and changing title.

**Comment by Gaurav0** [comment]
See https://github.com/emberjs/data/issues/4873
