### ISSUE TITLE
[BUG] Can't add tests from menu

### ISSUE THREAD

**Issue by maprules1000** [ember-cli/ember-twiddle#546]
When trying to add any test through the menu I get this error:

```
SyntaxError: Unexpected token } in JSON at position 395
    at JSON.parse (<anonymous>)
    at ember-twiddle-f01fea9….js:3
    at C (vendor-9da9463….js:23)
    at new R (vendor-9da9463….js:23)
    at i._updateTwiddleJson (ember-twiddle-f01fea9….js:3)
    at i.setTesting (ember-twiddle-f01fea9….js:3)
    at i.ensureTestingEnabled (ember-twiddle-f01fea9….js:3)
    at i.ensureTestingEnabled (ember-twiddle-f01fea9….js:3)
    at i.ensureTestingEnabled (ember-twiddle-f01fea9….js:2)
    at i.addIntegrationTestFile (ember-twiddle-f01fea9….js:1)
```

That stack, prettified in Chrome's dev tools, looks like this: 
```
                   case 11:
                        e.prev = 11,
                        e.t0 = e.catch(3),
                        this.set("isBuilding", !1),
                        t.default.isArray(e.t0) ? (this.set("buildErrors", e.t0),
                        e.t0.forEach(function(e) {
                            console.error(e)
       ---->        })) : e.t0 && console.error(e.t0);
                    case 15:
                    case "end":
                        return e.stop()
                    }
```
It looks like the only problem is an extra `)` in the compiled code.

I'm not sure how to fix this error since the un-transpiled [source](https://github.com/ember-cli/ember-twiddle/blob/master/app/mixins/app-builder.js) doesn't seem to have any issues.

**Comment by Gaurav0** [comment]
Unable to reproduce. https://ember-twiddle.com/36f6181496555ec0a842ab2b8e569352?openFiles=tests.acceptance.application-test.js%2Ctemplates.components.my-component.hbs

**Comment by maprules1000** [comment]
@Gaurav0 ok, it's working for me there, but could you also take a look at this twiddle? I still can't add tests here and I still get that same error in my console. 
[https://ember-twiddle.com/c106d6af281699b7eeb0f1bd33e35f4d](https://ember-twiddle.com/c106d6af281699b7eeb0f1bd33e35f4d)

**Comment by Gaurav0** [comment]
Addons need to be added to the addons hash, not the dependencies hash.
