### ISSUE TITLE
Could not find module `demo-app/router` imported from `demo-app/initializers/router`

### ISSUE THREAD

**Issue by aortbals** [ember-cli/ember-twiddle#55]
A [twiddle](http://ember-twiddle.com/245f05c2105f92768d04) from a few days ago that I made was working great - love the tool btw - but I'm now getting this error:

> Uncaught Error: Could not find module `demo-app/router` imported from `demo-app/initializers/router`

**Comment by aortbals** [comment]
Must be related to https://github.com/ember-cli/ember-twiddle/pull/51

**Comment by Gaurav0** [comment]
So the problem is there is now a default router.js required. Please create a router.js containing the following:

    import Ember from 'ember';
    var Router = Ember.Router.extend({
      location: 'none'
    });
    
    Router.map(function() {
   });
   
   export default Router;

**Comment by Gaurav0** [comment]
The file is created with new twiddles, but existing twiddles will need to add this. Please leave this open to see if we can come up with something that inserts it automatically into old twiddles.

**Comment by aortbals** [comment]
Indeed that did fix it. I agree though, it would be unfortunate if existing twiddles remaining broken from this change.

**Comment by joostdevries** [comment]
fix by @Gaurav0 has been deployed :-).

**Comment by aortbals** [comment]
Thanks @Gaurav0!
