### ISSUE TITLE
Not clear how to rename files

### ISSUE THREAD

**Issue by locks** [ember-cli/ember-twiddle#557]
I was giving a workshop and the attendees make a typo while creating a file. They then weren't sure how to rename the file, and only after a beat did I remember realize that "Move file" would do the trick.

**Comment by Gaurav0** [comment]
Agreed. I would accept a pull request to make this clearer, perhaps Move / Rename.

**Comment by kennethlarsen** [comment]
This is resolved by #578 so this issue can now be closed.
