### ISSUE TITLE
Github enterprise support

### ISSUE THREAD

**Issue by andytompkins** [ember-cli/ember-twiddle#559]
Hi,
Does this software work with Github enterprise? I see a github-enterprise torii provider in the source tree, and tried to switch to and configure that, but I am not making it very far. Is there any documentation on how to get this working with GHE? How do you handle needing both a client key and secret? I realize that exposing a secret in a client side app is bad, but I do not really understand how this would work without providing both key and secret? Any help would be really appreciated!!

**Comment by alexspeller** [comment]
It does not work with github enterprise at the moment.

Currently there is a server-side piece called gatekeeper. See the contributing guide for full details.

**Comment by andytompkins** [comment]
Ahhh! Thank you, that was very helpful. Got it working with my GHE with gatekeeper.

**Comment by Gaurav0** [comment]
Github Enterprise is supported.
