### ISSUE TITLE
Cannot use ember-data versions 2.13.x - 2.14.6

### ISSUE THREAD

**Issue by nbrookie** [ember-cli/ember-twiddle#560]
Ember twiddle does not work when specifying `ember-data` versions ranging from `2.13.0-beta.1` to `2.14.6`.

**Twiddle to replicate:** [Twiddle](https://ember-twiddle.com/59960127506d1a68618979ec3273dad8?openFiles=templates.application.hbs%2C)

Ex:
- in `twiddle.json`

  ```
  ...
  "ember": "release",
  "ember-data": "2.13.2"
  ...
  ```
- get the following error in the console:
![screen shot 2017-08-13 at 2 06 59 pm](https://user-images.githubusercontent.com/915868/29253399-c0f8ab24-8030-11e7-91d0-6c0527ea7636.png)

**Note:** Twiddle works just fine with ember-data `2.12.2` and below, and ember-data `2.14.7` and above.

**Comment by Gaurav0** [comment]
Sorry, for the moment the workaround is to move ember-data from addons to dependencies. This will load the traditional version of ember-data rather than the ember-data addon.

**Comment by acorncom** [comment]
Closing this as I believe it was resolved by https://github.com/ember-cli/ember-twiddle/pull/568 Please comment if it needs to be re-opened
