### ISSUE TITLE
Update with ember release since 2.12

### ISSUE THREAD

**Issue by myartsev** [ember-cli/ember-twiddle#563]
It looks like ember-twiddle is still stuck on v2.12, and Ember is currently on v2.15

**Comment by ykaragol** [comment]
When we try to use ember 2.15, we get the following error:

> Version or package not found or not a valid addon, error details: Error: No support for ember version "2.15.0". Supported versions: "1.13.13", "2.0.0", "2.0.3", "2.1.0", "2.2.0", "2.3.0", "2.4.0", "2.5.0", "2.6.0", "2.7.0", "2.8.0", "2.9.0", "2.10.0", "2.10.1", "2.11.0", "2.12.0"

**Comment by Gaurav0** [comment]
Updated to 2.16, could use help upgrading further.

**Comment by acorncom** [comment]
I'm going to close this issue in favor of https://github.com/ember-cli/ember-twiddle/issues/609 so we can consolidate notes there
