### ISSUE TITLE
ember twiddle binding prob

### ISSUE THREAD

**Issue by mehrajpasha** [ember-cli/ember-twiddle#574]
Hi, I was following this "https://ember-twiddle.com/7e10351fed541a2056b5a3d9b145d915?openFiles=templates.application.hbs%2C"  In the place of AVG and MAX I have binding values coming from another JSON object(i.e {{query.choice}})..while I'm getting values in controller I'm getting as {{query.choice}} I need actual binded value

**Comment by Gaurav0** [comment]
I don't think this is an ember twiddle issue, that's how Ember normally behaves.
