### ISSUE TITLE
Tests broken after Ember 2.14

### ISSUE THREAD

**Issue by sukima** [ember-cli/ember-twiddle#577]
I don;t know how there isn't an issue for this yet, but I searched.

## To reproduce:

1.  Visit https://ember-twiddle.com
2.  Check the **Run Tests** checkbox
3.  Note the lack of running tests and the console returns a syntax error

![Firefox screenshot](https://user-images.githubusercontent.com/70075/35944978-928cbb08-0c2c-11e8-8c35-13c257430f4b.png)
![Chrome screenshot2](https://user-images.githubusercontent.com/70075/35944980-92a61850-0c2c-11e8-8453-bcaae7d2f6d9.png)

Test do work for Ember version **< 2.14**.

**Comment by Gaurav0** [comment]
Thanks for reporting!

**Comment by sukima** [comment]
Any status on this?!

**Comment by Gaurav0** [comment]
Hi, no one seems to have worked on this yet. Feel free to do so.
