### ISSUE TITLE
Improve caching headers

### ISSUE THREAD

**Issue by joostdevries** [ember-cli/ember-twiddle#58]
Stef Penner [4:24 PM] 
looks like  vendor.js and ember-twiddle.js can be more aggressively cached

Stef Penner [4:24 PM]
they are never served straight from cache

**Comment by joostdevries** [comment]
@stefanpenner From what I can see they have caching headers for 4 hours. Just upped that to one year since we use fingerprinting.

**Comment by stefanpenner** [comment]
earlier the etags kept changing, now everything looks good. (unsure if it was directly related or not, but this looks good to me)
