### ISSUE TITLE
Ember 3.0

### ISSUE THREAD

**Issue by MrChriZ** [ember-cli/ember-twiddle#580]
Just tried to create a twiddle with Ember 3.0. (Release)
It doesn't appear to be working.
It never completes building.

**Comment by MrChriZ** [comment]
2.18 seems to be an issue as well.

**Comment by Gaurav0** [comment]
Latest working version is 2.16

**Comment by MrChriZ** [comment]
No error message is given, even in the Javascript console.
I also tried on the canary version with the same result.
If you select dependencies=> Ember.js=> release then the twiddle fails to build.
I think it would probably be handy if the github page indicates which versions of Ember is supported.

**Comment by Gaurav0** [comment]
Agreed. PRs accepted.

**Comment by chris-aeviator** [comment]
Coming through the search for a solution for `Ember.HTMLbars.compile()` in Ember 3.0 to this issue and tbieniek (ember slack community) hinted me that it is not part of the public API anymore.

**Comment by jrock2004** [comment]
Could it be that Ember Twiddle expects dependencies to be in bower vs npm? I know with 3.0, Ember is no longer releasing libraries to bower

**Comment by Gaurav0** [comment]
Verified that Ember.Htmlbats.compile is still public api.

**Comment by acorncom** [comment]
I'm going to close this in favor of https://github.com/ember-cli/ember-twiddle/issues/609 so we can consolidate notes about upgrading Twiddle to support the latest versions of Ember there
