### ISSUE TITLE
Upgrade Babel to v6

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-twiddle#593]
This is likely to be a challenging upgrade, due to the differences in the Babel transpiler in v.5 vs v.6. 

Babel 5 transpiles modules using code here: https://github.com/ember-cli/ember-cli/blob/06080981a582ddefadaf16fbcbd2d3b3d397dee6/lib/models/addon.js#L1738-L1754

while Babel 6 transpiles modules using code here: https://github.com/ember-cli/ember-cli/blob/37fcddc7b75cd71ee148bee98fec603ce1516195/lib/broccoli/babel-process-modules-only.js#L18-L25

**Expected steps:**

- [ ] 1. Upgrade ember-twiddle to use Babel 6 for its own transpilation
- [ ] 2. Send to client Babel 6 runtime from ember-cli-build.js
- [ ] 3. Change how modules are compiled on client in [ember-cli.js](https://github.com/ember-cli/ember-cli/blob/37fcddc7b75cd71ee148bee98fec603ce1516195/lib/broccoli/babel-process-modules-only.js#L18-L25)
- [ ] 4. Get most tests working - ensure compilation is correct.
- [ ] 5. Ensure addons still work even if compiled with Babel 5
- [ ] 6. Fix hbs plugin
- [ ] 7. Ensure tests still work on client (enable_testing: true).
- [ ] 8. Fix remaining tests.

**Comment by acorncom** [comment]
@Gaurav0 does the pR above mean this issue can already be closed? 👏
