### ISSUE TITLE
File browser instead of dropdowns for selecting files

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-cli/ember-twiddle#61]
Since ember-cli apps would have more number of files than a normal fiddle would, does it make sense to,
- Include a [file browser like interface](http://www.jstree.com/) on the left to open files(togglable)
- Support window splitting
- May be even a keyboard binding like `cmd+p` to show quick file selector

**Comment by joostdevries** [comment]
thanks, this is also covered in #10 and #34

**Comment by sivakumar-kailasam** [comment]
Oops didn't see that.

**Comment by joostdevries** [comment]
no probs :-)
