### ISSUE TITLE
Support Broccoli usage

### ISSUE THREAD

**Issue by acorncom** [ember-cli/ember-twiddle#612]
Something that @Gaurav0 mentioned, unclear on how this might work. Gaurav, have you experimented with this at all? Any pointers / thoughts on where someone interested might start?

**Comment by Gaurav0** [comment]
Not sure what you mean by broccoli usage.

**Comment by acorncom** [comment]
Not sure I do either 😉 It was a note I had from a conversation with you. If I'm off base, let's close this issue
