### ISSUE TITLE
Add support for RFC232 style tests

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-twiddle#617]
Requires https://github.com/ember-cli/ember-twiddle/issues/600

**Comment by Gaurav0** [comment]
This is fixed in v0.15.0. Please report bugs as new issues.

Example: https://ember-twiddle.com/2ad7133b2fb8bb246b5cb9cc11cb3bde

**Comment by sukima** [comment]
Is it possible to reopen this? The current released version on ember-twiddle.com breaks using the default blueprints requiring me copy paste the above example to my own twiddles.

**Comment by Gaurav0** [comment]
Please open a separate issue to update blueprints.
