### ISSUE TITLE
authentication issue while running twiddle in development mode

### ISSUE THREAD

**Issue by gokatz** [ember-cli/ember-twiddle#620]
When running twiddle in my machine (dev mode), I got this error while signing in using GitHub. 

![twiddle - dev](https://user-images.githubusercontent.com/15158776/41393308-c7bef1ac-6fc2-11e8-89e1-27ab3d2f54d8.png)

any help?

**Comment by acorncom** [comment]
You’re hitting issues because you need to be running s backend at that url: https://github.com/ember-cli/ember-twiddle/search?utf8=✓&q=authenticate&type=

Not sure where the code that runs there is located though ...

**Comment by gokatz** [comment]
I thought it is running! But, when running `node server.js` it just outputs the config.

![gatekeeper](https://user-images.githubusercontent.com/15158776/41424851-d0fabc10-701c-11e8-823c-a62f467c65ae.png)

**Comment by gokatz** [comment]
ah that's `node index.js` not `node server.js`. I think the docs needs to be updated. Will send a PR if needed.
