### ISSUE TITLE
Add support for ember-decorators

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-twiddle#625]
Requested by @nullvoxpopuli

Example Twiddle: https://canary.ember-twiddle.com/858ee42508e898cc0cf7478a1fed7583?openFiles=controllers.application.js%2C

See https://github.com/ember-decorators/babel-transforms/blob/v2.0.1/private/setup-babel.js#L53 for how babel needs to be setup.

**Comment by Gaurav0** [comment]
Fixed by #633

I forked your example twiddle and fixed it here: https://canary.ember-twiddle.com/5837aa39c1cb53be16caa941d9b68147

**Comment by NullVoxPopuli** [comment]
:+1:
