### ISSUE TITLE
Add support for async / await

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-twiddle#626]
Should I do this for tests only or always? Transpile to native promises or RSVP?

**Comment by rwjblue** [comment]
Hmm, does ember-twiddle currently support platforms that do not have native async/await support?

**Comment by Gaurav0** [comment]
AFAIK, no. We don't support MSIE or older versions of Mobile Safari ...

**Comment by Gaurav0** [comment]
But right now, Babel throws an error saying "await is a reserved word"

**Comment by rwjblue** [comment]
https://canary.ember-twiddle.com/6ed235534cb1d330aa5bc2b76b61ffd1?openFiles=routes.application.js%2C 

Seems to be working?

**Comment by rwjblue** [comment]
Though, we should tweak the preset setup a bit I think.

I think we should remove [this line](https://github.com/ember-cli/ember-twiddle/blob/d13b09f1f043b2f96cec9ec55b1bb0bdd7770282/app/services/ember-cli.js#L514).  Basically, we _only_ need to transpile modules, inline HBS, and the new modules plugin.  Anything else should be left alone, and therefore just leverage whats built into the browser...

**Comment by Gaurav0** [comment]
Whoops: Got the error because I put `async` in the wrong function!
