### ISSUE TITLE
Javascript spread operator not working

### ISSUE THREAD

**Issue by aaronlelevier** [ember-cli/ember-twiddle#635]
I had gone to this `ember-twiddle` before and it was working, but now it's not and points to the Javascript spread operator. Did a regression happen or do you know what may be causing this?  Here is the `ember-twiddle` project showing the error:

[https://ember-twiddle.com/4bb9c326a7e54c739b1f5a5023ccc805](https://ember-twiddle.com/4bb9c326a7e54c739b1f5a5023ccc805)

Here is a screenshot of the console error:

Thanks

<img width="1680" alt="screen shot 2018-08-09 at 4 37 13 pm" src="https://user-images.githubusercontent.com/5514112/43931357-e50248e8-9bf2-11e8-8407-22b49fe2b266.png">

**Comment by Gaurav0** [comment]
No. But I did change the env settings so you are now using browser (native) ES6 most of the time rather than Babel transpired.

**Comment by aaronlelevier** [comment]
I'm not sure if I understand. I'm using Chrome. Is it a browser setting that I have that's causing the error?

**Comment by knownasilya** [comment]
@Gaurav0 I think a transform plugin is missing, since object spread is not supported by chrome and would need a babel plugin.

**Comment by Gaurav0** [comment]
So it appears that the object spread operator is still in stage 2, and thus is not automatically supported by @babel/preset-env. Leaving this open.

**Comment by Gaurav0** [comment]
Fixed! https://canary.ember-twiddle.com/4bb9c326a7e54c739b1f5a5023ccc805

**Comment by aaronlelevier** [comment]
Thanks @quajo  and @Gaurav0
