### ISSUE TITLE
Access control origin errors for https://howq105a2c.execute-api.us-east-1.amazonaws.com/production/addon.....

### ISSUE THREAD

**Issue by edeis53** [ember-cli/ember-twiddle#638]
`Failed to load https://howq105a2c.execute-api.us-east-1.amazonaws.com/production/addon?ember_version=3.2.2&addon=liquid-fire&addon_version=^0.29.5: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://ember-twiddle.com' is therefore not allowed access. The response had HTTP status code 400.`

For the following twiddle:
`https://ember-twiddle.com/98c2ad1e52819ffd3d04bbb007d5ce06?openFiles=twiddle.json%2C`

**Comment by Gaurav0** [comment]
The `^` is not supported. Please specify exact version in addons hash in ember twiddle.
