### ISSUE TITLE
[bug] Regression - Cross-Origin Read Blocking error when attempting to run tests

### ISSUE THREAD

**Issue by mike-north** [ember-cli/ember-twiddle#640]
### To reproduce this problem

- go here: https://canary.ember-twiddle.com/a06ae7420d8d18e5907f45768237d1fb
- click the "run tests" checkbox

You'll see that the test UI is not shown. This twiddle worked fine for months -- I started to get reports on July 27 that this issue blocked people from seeing the QUnit UI.

**Comment by Gaurav0** [comment]
Here's the fixed version:

https://canary.ember-twiddle.com/410425e1676919ced96e7370d4dcdd4d?openFiles=tests.test-helper.js%2C

This is the cause:

https://github.com/ember-cli/ember-twiddle/issues/616
