### ISSUE TITLE
Can't sign in to Ember-Twiddle via Github

### ISSUE THREAD

**Issue by arthur5005** [ember-cli/ember-twiddle#650]
It's been a while since I've been back, but I tried to sign into ember-twiddle with github, on an incognito browser, and go this:

![screen shot 2019-01-02 at 5 15 01 pm](https://user-images.githubusercontent.com/697846/50620069-32289a00-0eb2-11e9-8123-fd753d58d2a5.png)

![screen shot 2019-01-02 at 5 18 00 pm](https://user-images.githubusercontent.com/697846/50620102-6d2acd80-0eb2-11e9-9b3e-c7c6b77a76a5.png)

**Comment by Gaurav0** [comment]
Incognito mode is not supported.
