### ISSUE TITLE
Basic twiddle module import?

### ISSUE THREAD

**Issue by theseyi** [ember-cli/ember-twiddle#653]
I'm trying to import a module I created in twiddle into another module (see twiddle below)
The documentation provides no guide on what the correct path is or even if this is possible?

https://ember-twiddle.com/59df3032c5daf321fe2a7c1ca23ae1a7?openFiles=controllers.application.js%2C
These all seems plausible but fail:
<img width="1419" alt="screen shot 2019-02-18 at 7 27 47 pm" src="https://user-images.githubusercontent.com/3725821/52988255-58978b80-33b3-11e9-85b0-ec0b3622501c.png">

```ts
import AutoBind from '../auto-bind';
import AutoBind from 'auto-bind';
import AutoBind from 'twiddle/auto-bind';
...
```

**Comment by gokatz** [comment]
Hi @theseyi,  I'm not entirely sure if the module system can pull `.auto-bind` file when importing in another module. Tried to get this done by moving the auto-bind logic to a `js` module and it worked.

https://ember-twiddle.com/ed02fb78396d8b361abfb4dd4e41943b?openFiles=controllers.application.js%2C

**Comment by theseyi** [comment]
thanks @gokatz totally bungled that!
