### ISSUE TITLE
Support for `@css-blocks/ember-cli`

### ISSUE THREAD

**Issue by amiller-gh** [ember-cli/ember-twiddle#657]
👋 Hi all!

I would like to host some runnable ember twiddle examples of [CSS Blocks](https://css-blocks.com) in an Ember app. However, when I add `@css-blocks/ember-cli` to `twiddle.json` the application hangs with a perpetual "Building..." message.

https://ember-twiddle.com/57b20467d824add6364cc47b3727d2dc

Looking at old issues, it appears this happens when https://github.com/joostdevries/twiddle-backend has trouble building an ember addon. I tried to pull down the project and spin up my own instance of it to see where the addon build is failing, but couldn't get it running – docker image dies with:

```
Step 17/23 : COPY addon-build-configs/$EMBER_VERSION/ember-cli-build.js /addon-builder/ember-cli-build.js
COPY failed: stat /var/lib/docker/tmp/docker-builder986033965/addon-build-configs/2.9.0/ember-cli-build.js: no such file or directory
```
l'Il keep poking at the docker image, but figured I'd open an issue here as well to see if anyone can easily help me debug.

**Comment by Gaurav0** [comment]
Add-ons with versions of Ember < 2.12 are officially deprecated.

**Comment by amiller-gh** [comment]
Okay! Update. Finally got the docker image working locally, was able to reproduce my bug and fix it in `@css-blocks/ember-cli@0.23.2`. I can now run the docker image against that version and see it build properly with no error. However, when I update the version in https://ember-twiddle.com/57b20467d824add6364cc47b3727d2dc, the build still hangs.

Before I go through the rigamarole of setting up `ember-twiddle` itself for development to debug more, can you take a peek in the uploaded modules and verify that `@css-blocks/ember-cli@0.23.2` built and uploaded properly, and this is a frontend build problem, not a module build problem?

**Comment by Gaurav0** [comment]
It is a module build issue. The addon did not successfully build and was not uploaded to S3.

I've copied the error message from the log here:

"Version or package not found or not a valid addon, error details: Error: Not valid addon: {\"code\":\"MethodNotAllowedError\",\"message\":\"GET is not allowed\"}"

I think the backend code is not properly escaping the "@"

**Comment by amiller-gh** [comment]
Ahh, well thats fun. Interesting that fetching appears to work locally for me. It appears that npm handles the `@` both escaped and un-escaped, but the `/` in the name messes it up (you'd think the registry would resolve the URL properly). Will have a PR up in the next few minutes.

Side note: theres another unrelated escaping bug in on frontend side that I'll open a second issue for. Has to do with files that contain multiple file endings, ex: `styles.block.css`.

**Comment by amiller-gh** [comment]
PR: https://github.com/joostdevries/twiddle-backend/pull/37

**Comment by amiller-gh** [comment]
Ref, other encoding issue: https://github.com/ember-cli/ember-twiddle/issues/658
