### ISSUE TITLE
Cannot sign in

### ISSUE THREAD

**Issue by mydea** [ember-cli/ember-twiddle#710]
I just tried to sign in on Firefox & Chromium multiple times. The OAuth window pops up and disappears immediately, and nothing happens. The button says "Signing in...". 
The console says:

```
[Torii] Using an OAuth redirect that loads your Ember App is deprecated and will be
              removed in a future release, as doing so is a potential security vulnerability.
              Hide this message by setting `allowUnsafeRedirect: true` in your Torii configuration.
```

**Comment by Gaurav0** [comment]
Hi, @mydea 

There was a github outage some hours ago. Try again now and confirm you are still getting an error.

The message you provided is a deprecation warning that I need to fix but appears normally. The logs indicate that you received a 404 from api.github.com.

**Comment by mydea** [comment]
Ah, it seems to be working now! Thank you :)
