### ISSUE TITLE
Twiddles don't work with old versions of Ember

### ISSUE THREAD

**Issue by elwayman02** [ember-cli/ember-twiddle#712]
I tried setting Twiddle to Ember/Ember-Data 3.8.x and generate a classic Ember component. It won't render the component and appears to be having build errors.

Example: https://ember-twiddle.com/0b0b97c956906844f62c3c50bea3dc7c?openFiles=components.my-component%5C.js%2Ctemplates.components.my-component%5C.hbs

**Comment by Gaurav0** [comment]
Thanks for testing / reporting.

**Comment by Gaurav0** [comment]
Backend fixed.
