### ISSUE TITLE
Issue creating a "js only" component

### ISSUE THREAD

**Issue by locks** [ember-cli/ember-twiddle#715]
When using the menu to create a "js only" component, this is the full content of the js file:

```


export default 
```

@Gaurav0 mentioned that the relevant code can be found at https://github.com/ember-cli/ember-twiddle/blob/e7e6732cfad7c0fb41238fb17141b455c966ff72/app/mixins/files.js#L123-L129.

**Comment by RajaSK05** [comment]
Any reason why this issue is still open?

**Comment by knownasilya** [comment]
Thanks!
