### ISSUE TITLE
Fiddle hangs on "building" with CORS error if addon version contains caret

### ISSUE THREAD

**Issue by gabrielgrant** [ember-cli/ember-twiddle#722]
Sending the request to build the project seems to be failing after adding an addon to a fiddle

From the console: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://howq105a2c.execute-api.us-east-1.amazonaws.com/produ…on?ember_version=3.18.1&addon=ember-mapbox-gl&addon_version=^1.0.1. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

Example: https://ember-twiddle.com/c9f21301be20398fdd75f7d4a38f73d1?openFiles=templates.application%5C.hbs%2C

**Comment by gabrielgrant** [comment]
Ah, seems to have been because I left the addon version as `^1.0.1` (copied from my package.json) rather than `1.0.1`. After removing the caret, the request seems to succeed.

**Comment by Gaurav0** [comment]
Sorry, version ranges are not supported at this time.

**Comment by gabrielgrant** [comment]
Yea, it totally makes sense to me to require a specific version. Only left this open thinking it would be nice if it failed a bit more gracefully, but obviously not high priority
