### ISSUE TITLE
[BUG] Cannot add two files of the same type, even if name is different.

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-twiddle#79]
Steps to reproduce:

Create new twiddle.
Add template, name it 'foo/template.hbs'
Try to add another template.

You are not prompted to change the name. In the console, you see the error "Uncaught Error: Assertion Failed: The id my-route.template.hbs has already been used with another record of type ember-twiddle@model:gist-file:".

**Comment by Gaurav0** [comment]
For now, this fix is deployed on https://ember-twiddle-gaurav.herokuapp.com

**Comment by rwjblue** [comment]
Fixed by #80.
