### ISSUE TITLE
Still cannot run older version of ember.js

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-twiddle#81]
See https://ember-twiddle-gaurav.herokuapp.com/e99546e0831d6d0251fc

Possibly loading / using the wrong version of ember-template-compiler?

**Comment by rwjblue** [comment]
We need to add the template compiler to `twiddle.json`.  We can use the default one from https://cdnjs.cloudflare.com/ajax/libs/ember.js/1.13.5/ember-template-compiler.js

**Comment by Gaurav0** [comment]
@rwjblue Thanks. The only issues now is that 

1) we no longer precompile templates
2) This breaks existing twiddles

**Comment by Gaurav0** [comment]
Fixed.
