### ISSUE TITLE
Allow import of an ember cli folder structure

### ISSUE THREAD

**Issue by abidmix** [ember-cli/ember-twiddle#88]
It would be great if the ember twiddle application would allow us  to import an ember-cli file structure residing on a user machine.

**Comment by Gaurav0** [comment]
I don't think that's possible due to security restrictions, but someone could write a separate addon to convert an ember-cli app to a twiddle gist.

**Comment by rwjblue** [comment]
Yeah, I agree that an addon that provides a local command is the best option.  Something like `ember gist` or somesuch.  It is somewhat tricky, as twiddle isn't a perfect ember-cli environment (addons don't work and whatnot), but it could get close...

**Comment by joostdevries** [comment]
This is most likely best done in an addon, closing this but like the idea :-)
