### ISSUE TITLE
Show a user's twiddles

### ISSUE THREAD

**Issue by joostdevries** [ember-cli/ember-twiddle#93]
Should be fairly simple now they all have a `twiddle.json`.

**Comment by Gaurav0** [comment]
Do you mean like find/replace functionality?

**Comment by joostdevries** [comment]
nah, more that you shouldn't have to know the slug per sé. We could have "Find twiddle" and "My twiddles" tabs for example.. (You also mentioned it in your presentation, now people have to copy the id from Gist)

**Comment by Gaurav0** [comment]
Oh, that. I meant a page or modal or dropdown showing what twiddles a user has that he can open. Not a search field.

**Comment by joostdevries** [comment]
remaned :-)

**Comment by miguelcobain** [comment]
@joostdevries I get the "My twiddles" part. Just find twiddles on the user's gist account. But how would "Find twiddles" work? Do you mean a filter on the user's twiddles or a global search of twiddles?

**Comment by Gaurav0** [comment]
Fixed by #200
