### ISSUE TITLE
rename autorun to auto-play

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-twiddle#97]
ember has the concept of auto-run,  think having this checkbox labelled as such is contextually confusing.

**Comment by Gaurav0** [comment]
On the other hand, it is called "Autorun JS" in JSBin

**Comment by joostdevries** [comment]
Live reload?

**Comment by stefanpenner** [comment]
> Live reload?

:+1:

**Comment by Gaurav0** [comment]
Good for new contributors.
